//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ZhiFang.WebLisService.WeblisService.RequestFormWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RequestFormWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class RequestFormWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadBarCodeFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadBarCodeCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefuseDownloadBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpgradeRequestFormOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpLoadRequestFormClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback AppliyUpLoadOperationCompleted;
        
        private System.Threading.SendOrPostCallback AppliyUpLoad_CreatNewBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AppliyUpLoad_BoErChengOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RequestFormWebService() {
            this.Url = global::ZhiFang.WebLisService.Properties.Settings.Default.ZhiFang_WebLisService_WeblisService_RequestFormWebService_RequestFormWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event DownloadBarCodeCompletedEventHandler DownloadBarCodeCompleted;
        
        /// <remarks/>
        public event DownloadBarCodeFlagCompletedEventHandler DownloadBarCodeFlagCompleted;
        
        /// <remarks/>
        public event DownloadBarCodeCancelCompletedEventHandler DownloadBarCodeCancelCompleted;
        
        /// <remarks/>
        public event RefuseDownloadBarCodeCompletedEventHandler RefuseDownloadBarCodeCompleted;
        
        /// <remarks/>
        public event UpgradeRequestFormCompletedEventHandler UpgradeRequestFormCompleted;
        
        /// <remarks/>
        public event UpLoadRequestFormClientCompletedEventHandler UpLoadRequestFormClientCompleted;
        
        /// <remarks/>
        public event AppliyUpLoadCompletedEventHandler AppliyUpLoadCompleted;
        
        /// <remarks/>
        public event AppliyUpLoad_CreatNewBarCodeCompletedEventHandler AppliyUpLoad_CreatNewBarCodeCompleted;
        
        /// <remarks/>
        public event AppliyUpLoad_BoErChengCompletedEventHandler AppliyUpLoad_BoErChengCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCode(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out System.Xml.XmlNode nodeBarCode, out System.Xml.XmlNode nodeNRequestItem, out System.Xml.XmlNode nodeNRequestForm, out string xmlWebLisOthers, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            nodeBarCode = ((System.Xml.XmlNode)(results[1]));
            nodeNRequestItem = ((System.Xml.XmlNode)(results[2]));
            nodeNRequestForm = ((System.Xml.XmlNode)(results[3]));
            xmlWebLisOthers = ((string)(results[4]));
            ReturnDescription = ((string)(results[5]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.DownloadBarCodeAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.DownloadBarCodeOperationCompleted == null)) {
                this.DownloadBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCodeOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.DownloadBarCodeOperationCompleted, userState);
        }
        
        private void OnDownloadBarCodeOperationCompleted(object arg) {
            if ((this.DownloadBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCodeCompleted(this, new DownloadBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCodeFlag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCodeFlag(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCodeFlag", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            ReturnDescription = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCodeFlagAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.DownloadBarCodeFlagAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCodeFlagAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.DownloadBarCodeFlagOperationCompleted == null)) {
                this.DownloadBarCodeFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCodeFlagOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCodeFlag", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.DownloadBarCodeFlagOperationCompleted, userState);
        }
        
        private void OnDownloadBarCodeFlagOperationCompleted(object arg) {
            if ((this.DownloadBarCodeFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCodeFlagCompleted(this, new DownloadBarCodeFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCodeCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCodeCancel(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCodeCancel", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            ReturnDescription = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCodeCancelAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.DownloadBarCodeCancelAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCodeCancelAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.DownloadBarCodeCancelOperationCompleted == null)) {
                this.DownloadBarCodeCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCodeCancelOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCodeCancel", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.DownloadBarCodeCancelOperationCompleted, userState);
        }
        
        private void OnDownloadBarCodeCancelOperationCompleted(object arg) {
            if ((this.DownloadBarCodeCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCodeCancelCompleted(this, new DownloadBarCodeCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RefuseDownloadBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RefuseDownloadBarCode(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out string ReturnDescription) {
            object[] results = this.Invoke("RefuseDownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            ReturnDescription = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RefuseDownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.RefuseDownloadBarCodeAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void RefuseDownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.RefuseDownloadBarCodeOperationCompleted == null)) {
                this.RefuseDownloadBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefuseDownloadBarCodeOperationCompleted);
            }
            this.InvokeAsync("RefuseDownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.RefuseDownloadBarCodeOperationCompleted, userState);
        }
        
        private void OnRefuseDownloadBarCodeOperationCompleted(object arg) {
            if ((this.RefuseDownloadBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefuseDownloadBarCodeCompleted(this, new RefuseDownloadBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpgradeRequestForm", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpgradeRequestForm(string SourceOrgID, string DestiOrgID, string BarCodeNo, string nodeBarCodeForm, string nodeNRequestForm, string nodeNRequestItem, string nodeOthers, out string WebLisFlag, out string ReturnDescription) {
            object[] results = this.Invoke("UpgradeRequestForm", new object[] {
                        SourceOrgID,
                        DestiOrgID,
                        BarCodeNo,
                        nodeBarCodeForm,
                        nodeNRequestForm,
                        nodeNRequestItem,
                        nodeOthers});
            WebLisFlag = ((string)(results[1]));
            ReturnDescription = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpgradeRequestFormAsync(string SourceOrgID, string DestiOrgID, string BarCodeNo, string nodeBarCodeForm, string nodeNRequestForm, string nodeNRequestItem, string nodeOthers) {
            this.UpgradeRequestFormAsync(SourceOrgID, DestiOrgID, BarCodeNo, nodeBarCodeForm, nodeNRequestForm, nodeNRequestItem, nodeOthers, null);
        }
        
        /// <remarks/>
        public void UpgradeRequestFormAsync(string SourceOrgID, string DestiOrgID, string BarCodeNo, string nodeBarCodeForm, string nodeNRequestForm, string nodeNRequestItem, string nodeOthers, object userState) {
            if ((this.UpgradeRequestFormOperationCompleted == null)) {
                this.UpgradeRequestFormOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpgradeRequestFormOperationCompleted);
            }
            this.InvokeAsync("UpgradeRequestForm", new object[] {
                        SourceOrgID,
                        DestiOrgID,
                        BarCodeNo,
                        nodeBarCodeForm,
                        nodeNRequestForm,
                        nodeNRequestItem,
                        nodeOthers}, this.UpgradeRequestFormOperationCompleted, userState);
        }
        
        private void OnUpgradeRequestFormOperationCompleted(object arg) {
            if ((this.UpgradeRequestFormCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpgradeRequestFormCompleted(this, new UpgradeRequestFormCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpLoadRequestFormClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpLoadRequestFormClient(string drs, string orgID, string jzType, out string strMsg) {
            object[] results = this.Invoke("UpLoadRequestFormClient", new object[] {
                        drs,
                        orgID,
                        jzType});
            strMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpLoadRequestFormClientAsync(string drs, string orgID, string jzType) {
            this.UpLoadRequestFormClientAsync(drs, orgID, jzType, null);
        }
        
        /// <remarks/>
        public void UpLoadRequestFormClientAsync(string drs, string orgID, string jzType, object userState) {
            if ((this.UpLoadRequestFormClientOperationCompleted == null)) {
                this.UpLoadRequestFormClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpLoadRequestFormClientOperationCompleted);
            }
            this.InvokeAsync("UpLoadRequestFormClient", new object[] {
                        drs,
                        orgID,
                        jzType}, this.UpLoadRequestFormClientOperationCompleted, userState);
        }
        
        private void OnUpLoadRequestFormClientOperationCompleted(object arg) {
            if ((this.UpLoadRequestFormClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpLoadRequestFormClientCompleted(this, new UpLoadRequestFormClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AppliyUpLoad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AppliyUpLoad(string xmlData, string orgID, string jzType, out string sMsg) {
            object[] results = this.Invoke("AppliyUpLoad", new object[] {
                        xmlData,
                        orgID,
                        jzType});
            sMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AppliyUpLoadAsync(string xmlData, string orgID, string jzType) {
            this.AppliyUpLoadAsync(xmlData, orgID, jzType, null);
        }
        
        /// <remarks/>
        public void AppliyUpLoadAsync(string xmlData, string orgID, string jzType, object userState) {
            if ((this.AppliyUpLoadOperationCompleted == null)) {
                this.AppliyUpLoadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppliyUpLoadOperationCompleted);
            }
            this.InvokeAsync("AppliyUpLoad", new object[] {
                        xmlData,
                        orgID,
                        jzType}, this.AppliyUpLoadOperationCompleted, userState);
        }
        
        private void OnAppliyUpLoadOperationCompleted(object arg) {
            if ((this.AppliyUpLoadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppliyUpLoadCompleted(this, new AppliyUpLoadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AppliyUpLoad_CreatNewBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AppliyUpLoad_CreatNewBarCode(string xmlData, string orgID, string jzType, out string sMsg) {
            object[] results = this.Invoke("AppliyUpLoad_CreatNewBarCode", new object[] {
                        xmlData,
                        orgID,
                        jzType});
            sMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AppliyUpLoad_CreatNewBarCodeAsync(string xmlData, string orgID, string jzType) {
            this.AppliyUpLoad_CreatNewBarCodeAsync(xmlData, orgID, jzType, null);
        }
        
        /// <remarks/>
        public void AppliyUpLoad_CreatNewBarCodeAsync(string xmlData, string orgID, string jzType, object userState) {
            if ((this.AppliyUpLoad_CreatNewBarCodeOperationCompleted == null)) {
                this.AppliyUpLoad_CreatNewBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppliyUpLoad_CreatNewBarCodeOperationCompleted);
            }
            this.InvokeAsync("AppliyUpLoad_CreatNewBarCode", new object[] {
                        xmlData,
                        orgID,
                        jzType}, this.AppliyUpLoad_CreatNewBarCodeOperationCompleted, userState);
        }
        
        private void OnAppliyUpLoad_CreatNewBarCodeOperationCompleted(object arg) {
            if ((this.AppliyUpLoad_CreatNewBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppliyUpLoad_CreatNewBarCodeCompleted(this, new AppliyUpLoad_CreatNewBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AppliyUpLoad_BoErCheng", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool AppliyUpLoad_BoErCheng(string xmlData, string orgID, out string sMsg) {
            object[] results = this.Invoke("AppliyUpLoad_BoErCheng", new object[] {
                        xmlData,
                        orgID});
            sMsg = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void AppliyUpLoad_BoErChengAsync(string xmlData, string orgID) {
            this.AppliyUpLoad_BoErChengAsync(xmlData, orgID, null);
        }
        
        /// <remarks/>
        public void AppliyUpLoad_BoErChengAsync(string xmlData, string orgID, object userState) {
            if ((this.AppliyUpLoad_BoErChengOperationCompleted == null)) {
                this.AppliyUpLoad_BoErChengOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppliyUpLoad_BoErChengOperationCompleted);
            }
            this.InvokeAsync("AppliyUpLoad_BoErCheng", new object[] {
                        xmlData,
                        orgID}, this.AppliyUpLoad_BoErChengOperationCompleted, userState);
        }
        
        private void OnAppliyUpLoad_BoErChengOperationCompleted(object arg) {
            if ((this.AppliyUpLoad_BoErChengCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppliyUpLoad_BoErChengCompleted(this, new AppliyUpLoad_BoErChengCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DownloadBarCodeCompletedEventHandler(object sender, DownloadBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeBarCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeNRequestItem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeNRequestForm {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string xmlWebLisOthers {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DownloadBarCodeFlagCompletedEventHandler(object sender, DownloadBarCodeFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCodeFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCodeFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void DownloadBarCodeCancelCompletedEventHandler(object sender, DownloadBarCodeCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCodeCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCodeCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RefuseDownloadBarCodeCompletedEventHandler(object sender, RefuseDownloadBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefuseDownloadBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RefuseDownloadBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpgradeRequestFormCompletedEventHandler(object sender, UpgradeRequestFormCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpgradeRequestFormCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpgradeRequestFormCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string WebLisFlag {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpLoadRequestFormClientCompletedEventHandler(object sender, UpLoadRequestFormClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpLoadRequestFormClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpLoadRequestFormClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AppliyUpLoadCompletedEventHandler(object sender, AppliyUpLoadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppliyUpLoadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AppliyUpLoadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AppliyUpLoad_CreatNewBarCodeCompletedEventHandler(object sender, AppliyUpLoad_CreatNewBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppliyUpLoad_CreatNewBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AppliyUpLoad_CreatNewBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AppliyUpLoad_BoErChengCompletedEventHandler(object sender, AppliyUpLoad_BoErChengCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppliyUpLoad_BoErChengCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AppliyUpLoad_BoErChengCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string sMsg {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591