//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiFang.WebLisService.WSRBAC_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSRBAC_Service.WSRbacSoap")]
    public interface WSRbacSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.HelloWorldResponse HelloWorld(ZhiFang.WebLisService.WSRBAC_Service.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserInfo", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.getUserInfoResponse getUserInfo(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserOrgInfo", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoResponse getUserOrgInfo(ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.LoginResponse Login(ZhiFang.WebLisService.WSRBAC_Service.LoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPermissibilityRunModules", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesResponse GetPermissibilityRunModules(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPermissibilityRunModule", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleResponse GetPermissibilityRunModule(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPermissibilityModuleButtons", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsResponse GetPermissibilityModuleButtons(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 PostName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserInfoListByPost", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostResponse getUserInfoListByPost(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Account 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPostInfoListByUser", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserResponse getPostInfoListByUser(ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 userId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassWord", ReplyAction="*")]
        ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordResponse ChangePassWord(ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ZhiFang.WebLisService.WSRBAC_Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ZhiFang.WebLisService.WSRBAC_Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getUserInfoRequestBody Body;
        
        public getUserInfoRequest() {
        }
        
        public getUserInfoRequest(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        public getUserInfoRequestBody() {
        }
        
        public getUserInfoRequestBody(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getUserInfoResponseBody Body;
        
        public getUserInfoResponse() {
        }
        
        public getUserInfoResponse(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserInfoResult;
        
        public getUserInfoResponseBody() {
        }
        
        public getUserInfoResponseBody(string getUserInfoResult) {
            this.getUserInfoResult = getUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserOrgInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserOrgInfo", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoRequestBody Body;
        
        public getUserOrgInfoRequest() {
        }
        
        public getUserOrgInfoRequest(ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserOrgInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        public getUserOrgInfoRequestBody() {
        }
        
        public getUserOrgInfoRequestBody(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserOrgInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserOrgInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoResponseBody Body;
        
        public getUserOrgInfoResponse() {
        }
        
        public getUserOrgInfoResponse(ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserOrgInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserOrgInfoResult;
        
        public getUserOrgInfoResponseBody() {
        }
        
        public getUserOrgInfoResponseBody(string getUserOrgInfoResult) {
            this.getUserOrgInfoResult = getUserOrgInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ZhiFang.WebLisService.WSRBAC_Service.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string UserName, string Password) {
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ZhiFang.WebLisService.WSRBAC_Service.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LoginResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descr;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(bool LoginResult, string descr) {
            this.LoginResult = LoginResult;
            this.descr = descr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissibilityRunModulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissibilityRunModules", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesRequestBody Body;
        
        public GetPermissibilityRunModulesRequest() {
        }
        
        public GetPermissibilityRunModulesRequest(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissibilityRunModulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        public GetPermissibilityRunModulesRequestBody() {
        }
        
        public GetPermissibilityRunModulesRequestBody(string UserName) {
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissibilityRunModulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissibilityRunModulesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesResponseBody Body;
        
        public GetPermissibilityRunModulesResponse() {
        }
        
        public GetPermissibilityRunModulesResponse(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissibilityRunModulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPermissibilityRunModulesResult;
        
        public GetPermissibilityRunModulesResponseBody() {
        }
        
        public GetPermissibilityRunModulesResponseBody(string GetPermissibilityRunModulesResult) {
            this.GetPermissibilityRunModulesResult = GetPermissibilityRunModulesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissibilityRunModuleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissibilityRunModule", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleRequestBody Body;
        
        public GetPermissibilityRunModuleRequest() {
        }
        
        public GetPermissibilityRunModuleRequest(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissibilityRunModuleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModuleNo;
        
        public GetPermissibilityRunModuleRequestBody() {
        }
        
        public GetPermissibilityRunModuleRequestBody(string UserName, string ModuleNo) {
            this.UserName = UserName;
            this.ModuleNo = ModuleNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissibilityRunModuleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissibilityRunModuleResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleResponseBody Body;
        
        public GetPermissibilityRunModuleResponse() {
        }
        
        public GetPermissibilityRunModuleResponse(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissibilityRunModuleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool GetPermissibilityRunModuleResult;
        
        public GetPermissibilityRunModuleResponseBody() {
        }
        
        public GetPermissibilityRunModuleResponseBody(bool GetPermissibilityRunModuleResult) {
            this.GetPermissibilityRunModuleResult = GetPermissibilityRunModuleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissibilityModuleButtonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissibilityModuleButtons", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsRequestBody Body;
        
        public GetPermissibilityModuleButtonsRequest() {
        }
        
        public GetPermissibilityModuleButtonsRequest(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissibilityModuleButtonsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ModuleNo;
        
        public GetPermissibilityModuleButtonsRequestBody() {
        }
        
        public GetPermissibilityModuleButtonsRequestBody(string UserName, string ModuleNo) {
            this.UserName = UserName;
            this.ModuleNo = ModuleNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPermissibilityModuleButtonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPermissibilityModuleButtonsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsResponseBody Body;
        
        public GetPermissibilityModuleButtonsResponse() {
        }
        
        public GetPermissibilityModuleButtonsResponse(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPermissibilityModuleButtonsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPermissibilityModuleButtonsResult;
        
        public GetPermissibilityModuleButtonsResponseBody() {
        }
        
        public GetPermissibilityModuleButtonsResponseBody(string GetPermissibilityModuleButtonsResult) {
            this.GetPermissibilityModuleButtonsResult = GetPermissibilityModuleButtonsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoListByPostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoListByPost", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostRequestBody Body;
        
        public getUserInfoListByPostRequest() {
        }
        
        public getUserInfoListByPostRequest(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserInfoListByPostRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PostName;
        
        public getUserInfoListByPostRequestBody() {
        }
        
        public getUserInfoListByPostRequestBody(string PostName) {
            this.PostName = PostName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserInfoListByPostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserInfoListByPostResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostResponseBody Body;
        
        public getUserInfoListByPostResponse() {
        }
        
        public getUserInfoListByPostResponse(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUserInfoListByPostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUserInfoListByPostResult;
        
        public getUserInfoListByPostResponseBody() {
        }
        
        public getUserInfoListByPostResponseBody(string getUserInfoListByPostResult) {
            this.getUserInfoListByPostResult = getUserInfoListByPostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPostInfoListByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPostInfoListByUser", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserRequestBody Body;
        
        public getPostInfoListByUserRequest() {
        }
        
        public getPostInfoListByUserRequest(ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPostInfoListByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Account;
        
        public getPostInfoListByUserRequestBody() {
        }
        
        public getPostInfoListByUserRequestBody(string Account) {
            this.Account = Account;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPostInfoListByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPostInfoListByUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserResponseBody Body;
        
        public getPostInfoListByUserResponse() {
        }
        
        public getPostInfoListByUserResponse(ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPostInfoListByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPostInfoListByUserResult;
        
        public getPostInfoListByUserResponseBody() {
        }
        
        public getPostInfoListByUserResponseBody(string getPostInfoListByUserResult) {
            this.getPostInfoListByUserResult = getPostInfoListByUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePassWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassWord", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordRequestBody Body;
        
        public ChangePassWordRequest() {
        }
        
        public ChangePassWordRequest(ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePassWordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userpwd;
        
        public ChangePassWordRequestBody() {
        }
        
        public ChangePassWordRequestBody(string userId, string userpwd) {
            this.userId = userId;
            this.userpwd = userpwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePassWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordResponseBody Body;
        
        public ChangePassWordResponse() {
        }
        
        public ChangePassWordResponse(ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePassWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePassWordResult;
        
        public ChangePassWordResponseBody() {
        }
        
        public ChangePassWordResponseBody(bool ChangePassWordResult) {
            this.ChangePassWordResult = ChangePassWordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSRbacSoapChannel : ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSRbacSoapClient : System.ServiceModel.ClientBase<ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap>, ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap {
        
        public WSRbacSoapClient() {
        }
        
        public WSRbacSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSRbacSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRbacSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSRbacSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.HelloWorldResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.HelloWorld(ZhiFang.WebLisService.WSRBAC_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ZhiFang.WebLisService.WSRBAC_Service.HelloWorldRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.HelloWorldRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.HelloWorldRequestBody();
            ZhiFang.WebLisService.WSRBAC_Service.HelloWorldResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.getUserInfoResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.getUserInfo(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoRequest request) {
            return base.Channel.getUserInfo(request);
        }
        
        public string getUserInfo(string UserName) {
            ZhiFang.WebLisService.WSRBAC_Service.getUserInfoRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.getUserInfoRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.getUserInfoRequestBody();
            inValue.Body.UserName = UserName;
            ZhiFang.WebLisService.WSRBAC_Service.getUserInfoResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).getUserInfo(inValue);
            return retVal.Body.getUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.getUserOrgInfo(ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoRequest request) {
            return base.Channel.getUserOrgInfo(request);
        }
        
        public string getUserOrgInfo(string UserName) {
            ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoRequestBody();
            inValue.Body.UserName = UserName;
            ZhiFang.WebLisService.WSRBAC_Service.getUserOrgInfoResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).getUserOrgInfo(inValue);
            return retVal.Body.getUserOrgInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.LoginResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.Login(ZhiFang.WebLisService.WSRBAC_Service.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public bool Login(string UserName, string Password, out string descr) {
            ZhiFang.WebLisService.WSRBAC_Service.LoginRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.LoginRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.LoginRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            ZhiFang.WebLisService.WSRBAC_Service.LoginResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).Login(inValue);
            descr = retVal.Body.descr;
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.GetPermissibilityRunModules(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesRequest request) {
            return base.Channel.GetPermissibilityRunModules(request);
        }
        
        public string GetPermissibilityRunModules(string UserName) {
            ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesRequestBody();
            inValue.Body.UserName = UserName;
            ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModulesResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).GetPermissibilityRunModules(inValue);
            return retVal.Body.GetPermissibilityRunModulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.GetPermissibilityRunModule(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleRequest request) {
            return base.Channel.GetPermissibilityRunModule(request);
        }
        
        public bool GetPermissibilityRunModule(string UserName, string ModuleNo) {
            ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.ModuleNo = ModuleNo;
            ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityRunModuleResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).GetPermissibilityRunModule(inValue);
            return retVal.Body.GetPermissibilityRunModuleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.GetPermissibilityModuleButtons(ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsRequest request) {
            return base.Channel.GetPermissibilityModuleButtons(request);
        }
        
        public string GetPermissibilityModuleButtons(string UserName, string ModuleNo) {
            ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.ModuleNo = ModuleNo;
            ZhiFang.WebLisService.WSRBAC_Service.GetPermissibilityModuleButtonsResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).GetPermissibilityModuleButtons(inValue);
            return retVal.Body.GetPermissibilityModuleButtonsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.getUserInfoListByPost(ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostRequest request) {
            return base.Channel.getUserInfoListByPost(request);
        }
        
        public string getUserInfoListByPost(string PostName) {
            ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostRequestBody();
            inValue.Body.PostName = PostName;
            ZhiFang.WebLisService.WSRBAC_Service.getUserInfoListByPostResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).getUserInfoListByPost(inValue);
            return retVal.Body.getUserInfoListByPostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.getPostInfoListByUser(ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserRequest request) {
            return base.Channel.getPostInfoListByUser(request);
        }
        
        public string getPostInfoListByUser(string Account) {
            ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserRequestBody();
            inValue.Body.Account = Account;
            ZhiFang.WebLisService.WSRBAC_Service.getPostInfoListByUserResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).getPostInfoListByUser(inValue);
            return retVal.Body.getPostInfoListByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordResponse ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap.ChangePassWord(ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordRequest request) {
            return base.Channel.ChangePassWord(request);
        }
        
        public bool ChangePassWord(string userId, string userpwd) {
            ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordRequest inValue = new ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordRequest();
            inValue.Body = new ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.userpwd = userpwd;
            ZhiFang.WebLisService.WSRBAC_Service.ChangePassWordResponse retVal = ((ZhiFang.WebLisService.WSRBAC_Service.WSRbacSoap)(this)).ChangePassWord(inValue);
            return retVal.Body.ChangePassWordResult;
        }
    }
}
