//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiFang.ReagentSys.Client.Service_HIS_WangJing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="Service_HIS_WangJing.WebLisServiceSoap")]
    public interface WebLisServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 Input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.LIS.BS.WebSHIJIService.PHTranOut", ReplyAction="*")]
        ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutResponse PHTranOut(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 Input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.LIS.BS.WebSHIJIService.SendInitInfo", ReplyAction="*")]
        ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoResponse SendInitInfo(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 Input 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.LIS.BS.WebSHIJIService.SynInciInfo", ReplyAction="*")]
        ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoResponse SynInciInfo(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PHTranOutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PHTranOut", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutRequestBody Body;
        
        public PHTranOutRequest() {
        }
        
        public PHTranOutRequest(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class PHTranOutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Input;
        
        public PHTranOutRequestBody() {
        }
        
        public PHTranOutRequestBody(string Input) {
            this.Input = Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PHTranOutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PHTranOutResponse", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutResponseBody Body;
        
        public PHTranOutResponse() {
        }
        
        public PHTranOutResponse(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class PHTranOutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PHTranOutResult;
        
        public PHTranOutResponseBody() {
        }
        
        public PHTranOutResponseBody(string PHTranOutResult) {
            this.PHTranOutResult = PHTranOutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendInitInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendInitInfo", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoRequestBody Body;
        
        public SendInitInfoRequest() {
        }
        
        public SendInitInfoRequest(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SendInitInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Input;
        
        public SendInitInfoRequestBody() {
        }
        
        public SendInitInfoRequestBody(string Input) {
            this.Input = Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendInitInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendInitInfoResponse", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoResponseBody Body;
        
        public SendInitInfoResponse() {
        }
        
        public SendInitInfoResponse(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SendInitInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendInitInfoResult;
        
        public SendInitInfoResponseBody() {
        }
        
        public SendInitInfoResponseBody(string SendInitInfoResult) {
            this.SendInitInfoResult = SendInitInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SynInciInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SynInciInfo", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoRequestBody Body;
        
        public SynInciInfoRequest() {
        }
        
        public SynInciInfoRequest(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SynInciInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Input;
        
        public SynInciInfoRequestBody() {
        }
        
        public SynInciInfoRequestBody(string Input) {
            this.Input = Input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SynInciInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SynInciInfoResponse", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoResponseBody Body;
        
        public SynInciInfoResponse() {
        }
        
        public SynInciInfoResponse(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SynInciInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SynInciInfoResult;
        
        public SynInciInfoResponseBody() {
        }
        
        public SynInciInfoResponseBody(string SynInciInfoResult) {
            this.SynInciInfoResult = SynInciInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebLisServiceSoapChannel : ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebLisServiceSoapClient : System.ServiceModel.ClientBase<ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap>, ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap {
        
        public WebLisServiceSoapClient() {
        }
        
        public WebLisServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebLisServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebLisServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebLisServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutResponse ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap.PHTranOut(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutRequest request) {
            return base.Channel.PHTranOut(request);
        }
        
        public string PHTranOut(string Input) {
            ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutRequest inValue = new ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutRequest();
            inValue.Body = new ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutRequestBody();
            inValue.Body.Input = Input;
            ZhiFang.ReagentSys.Client.Service_HIS_WangJing.PHTranOutResponse retVal = ((ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap)(this)).PHTranOut(inValue);
            return retVal.Body.PHTranOutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoResponse ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap.SendInitInfo(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoRequest request) {
            return base.Channel.SendInitInfo(request);
        }
        
        public string SendInitInfo(string Input) {
            ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoRequest inValue = new ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoRequest();
            inValue.Body = new ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoRequestBody();
            inValue.Body.Input = Input;
            ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SendInitInfoResponse retVal = ((ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap)(this)).SendInitInfo(inValue);
            return retVal.Body.SendInitInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoResponse ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap.SynInciInfo(ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoRequest request) {
            return base.Channel.SynInciInfo(request);
        }
        
        public string SynInciInfo(string Input) {
            ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoRequest inValue = new ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoRequest();
            inValue.Body = new ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoRequestBody();
            inValue.Body.Input = Input;
            ZhiFang.ReagentSys.Client.Service_HIS_WangJing.SynInciInfoResponse retVal = ((ZhiFang.ReagentSys.Client.Service_HIS_WangJing.WebLisServiceSoap)(this)).SynInciInfo(inValue);
            return retVal.Body.SynInciInfoResult;
        }
    }
}
