{
	success:true,
	ResultDataValue:{
		count:10,
		list:[{
			NRequestItem_Id:'1',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三1',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'1',
			NRequestItem_ItemPriceType:'1'
		},{
			NRequestItem_Id:'2',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三2',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'1',
			NRequestItem_ItemPriceType:'2'
		},{
			NRequestItem_Id:'3',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三3',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'2'
		},{
			NRequestItem_Id:'4',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三4',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'3'
		},{
			NRequestItem_Id:'5',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'3'
		},{
			NRequestItem_Id:'6',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'0'
		},{
			NRequestItem_Id:'7',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'1'
		},{
			NRequestItem_Id:'8',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'2'
		},{
			NRequestItem_Id:'9',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'3'
		},{
			NRequestItem_Id:'10',
			NRequestItem_Lab_Name:'送检单位1',
			NRequestItem_Dept_Name:'科室1',
			NRequestItem_U_Name:'张三',
			NRequestItem_BarCodeNo:'1101',
			NRequestItem_Item_Name:'项目1',
			NRequestItem_IsLocked:'0',
			NRequestItem_ItemPriceType:'4'
		}]
	}
}
