{
	success:true,
	ErrorInfo:'',
	Tree:[{
		tid:'04',
		text:'合同价格设置',
		expanded:true,
		leaf:true,
		iconCls:'button-config',
		className:'Shell.class.pki.contractprice.App'
	},{
		tid:'01',
		text:'经销商项目阶梯价格维护',
		expanded:true,
		leaf:true,
		iconCls:'button-config',
		className:'Shell.class.pki.dealer.ItemStepPriceApp'
	},{
		tid:'02',
		text:'经销商销售维护',
		expanded:true,
		leaf:true,
		iconCls:'button-config',
		className:'Shell.class.pki.dealer.SellerApp'
	},{
		tid:'03',
		text:'销售经销商维护',
		expanded:true,
		leaf:true,
		iconCls:'button-config',
		className:'Shell.class.pki.seller.DealerApp'
	},{
		tid:'05',
		text:'开票方设置',
		expanded:true,
		leaf:true,
		iconCls:'button-config',
		className:'Shell.class.pki.billingunit.Grid'
	},{
		tid:'06',
		text:'财务处理',
		expanded:true,
		leaf:false,
		iconCls:'button-check',
		Tree:[{
			tid:'0607',
			text:'财务状态查询',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance.Grid'
		},{
			tid:'0601',
			text:'对账快捷锁定',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance.LockAQuick'
		},{
			tid:'0602',
			text:'对账锁定',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance.LockAGrid'
		},{
			tid:'0603',
			text:'免单操作',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance.FreeSingleGrid'
		},{
			tid:'0604',
			text:'个人开票',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance.PersonGrid'
		},{
			tid:'0605',
			text:'阶梯价格计算',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance.StepPriceGrid'
		},{
			tid:'0606',
			text:'财务锁定',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance.LockFGrid'
		}]
	},{
		tid:'07',
		text:'财务处理2',
		expanded:true,
		leaf:false,
		iconCls:'button-check',
		Tree:[{
			tid:'0707',
			text:'财务状态查询',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance2.Grid'
		},{
			tid:'0701',
			text:'对账快捷锁定',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance2.LockAQuick'
		},{
			tid:'0702',
			text:'对账锁定',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance2.LockAGrid'
		},{
			tid:'0703',
			text:'免单操作',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance2.FreeSingleGrid'
		},{
			tid:'0704',
			text:'个人开票',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance2.PersonGrid'
		},{
			tid:'0705',
			text:'阶梯价格计算',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance2.StepPriceGrid'
		},{
			tid:'0706',
			text:'财务锁定',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.balance2.LockFGrid'
		}]
	},{
		tid:'08',
		text:'测试',
		expanded:true,
		leaf:false,
		iconCls:'button-check',
		Tree:[{
			tid:'0801',
			text:'合同价格查询',
			expanded:true,
			leaf:true,
			iconCls:'button-check',
			className:'Shell.class.pki.contractprice.SearchGrid'
		},{
			tid:'0802',
			text:'送检单位合同维护',
			expanded:true,
			leaf:true,
			iconCls:'button-config',
			className:'Shell.class.pki.contractprice.App2'
		},{
			tid:'0803',
			text:'合同价格设置',
			expanded:true,
			leaf:true,
			iconCls:'button-config',
			className:'Shell.class.pki.contractprice.App1'
		},{
			tid:'0804',
			text:'经销商项目维护',
			expanded:true,
			leaf:true,
			iconCls:'button-config',
			className:'Shell.class.pki.dealer.ItemApp'
		},{
			tid:'0805',
			text:'经销商项目阶梯价格维护',
			expanded:true,
			leaf:true,
			iconCls:'button-config',
			className:'Shell.class.pki.dealer.ItemStepPriceApp2'
		},{
			tid:'0805',
			text:'送检单位项目维护',
			expanded:true,
			leaf:true,
			iconCls:'button-config',
			className:'Shell.class.pki.laboratory.ItemApp'
		},{
			tid:'0806',
			text:'报表查询基础列表',
			expanded:true,
			leaf:true,
			iconCls:'button-config',
			className:'Shell.class.pki.report.BasicGrid'
		}]
	}]
}
