//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ZhiFang.WebLisService.SampleSwapInterface {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ASoap", Namespace="http://tempuri.org/")]
    public partial class A : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DownloadBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadBarCodeStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadBarCodeCancelOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadBarCodeFlagOperationCompleted;
        
        private System.Threading.SendOrPostCallback RefuseDownloadBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadBarCode_yzOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public A() {
            this.Url = global::ZhiFang.WebLisService.Properties.Settings.Default.ZhiFang_WebLisService_SampleSwapInterface_A;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DownloadBarCodeCompletedEventHandler DownloadBarCodeCompleted;
        
        /// <remarks/>
        public event DownloadBarCodeStrCompletedEventHandler DownloadBarCodeStrCompleted;
        
        /// <remarks/>
        public event DownloadBarCodeCancelCompletedEventHandler DownloadBarCodeCancelCompleted;
        
        /// <remarks/>
        public event DownloadBarCodeFlagCompletedEventHandler DownloadBarCodeFlagCompleted;
        
        /// <remarks/>
        public event RefuseDownloadBarCodeCompletedEventHandler RefuseDownloadBarCodeCompleted;
        
        /// <remarks/>
        public event DownloadBarCode_yzCompletedEventHandler DownloadBarCode_yzCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCode(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out System.Xml.XmlNode nodeBarCode, out System.Xml.XmlNode nodeNRequestItem, out System.Xml.XmlNode nodeNRequestForm, out string xmlWebLisOthers, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            nodeBarCode = ((System.Xml.XmlNode)(results[1]));
            nodeNRequestItem = ((System.Xml.XmlNode)(results[2]));
            nodeNRequestForm = ((System.Xml.XmlNode)(results[3]));
            xmlWebLisOthers = ((string)(results[4]));
            ReturnDescription = ((string)(results[5]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.DownloadBarCodeAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.DownloadBarCodeOperationCompleted == null)) {
                this.DownloadBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCodeOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.DownloadBarCodeOperationCompleted, userState);
        }
        
        private void OnDownloadBarCodeOperationCompleted(object arg) {
            if ((this.DownloadBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCodeCompleted(this, new DownloadBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCodeStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCodeStr(string DestiOrgID, string BarCodeNo, string strWebLiser, out string strBarCode, out string strNRequestItem, out string strNRequestForm, out string xmlWebLisOthers, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCodeStr", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        strWebLiser});
            strBarCode = ((string)(results[1]));
            strNRequestItem = ((string)(results[2]));
            strNRequestForm = ((string)(results[3]));
            xmlWebLisOthers = ((string)(results[4]));
            ReturnDescription = ((string)(results[5]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCodeStrAsync(string DestiOrgID, string BarCodeNo, string strWebLiser) {
            this.DownloadBarCodeStrAsync(DestiOrgID, BarCodeNo, strWebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCodeStrAsync(string DestiOrgID, string BarCodeNo, string strWebLiser, object userState) {
            if ((this.DownloadBarCodeStrOperationCompleted == null)) {
                this.DownloadBarCodeStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCodeStrOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCodeStr", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        strWebLiser}, this.DownloadBarCodeStrOperationCompleted, userState);
        }
        
        private void OnDownloadBarCodeStrOperationCompleted(object arg) {
            if ((this.DownloadBarCodeStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCodeStrCompleted(this, new DownloadBarCodeStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCodeCancel", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCodeCancel(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCodeCancel", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            ReturnDescription = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCodeCancelAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.DownloadBarCodeCancelAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCodeCancelAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.DownloadBarCodeCancelOperationCompleted == null)) {
                this.DownloadBarCodeCancelOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCodeCancelOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCodeCancel", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.DownloadBarCodeCancelOperationCompleted, userState);
        }
        
        private void OnDownloadBarCodeCancelOperationCompleted(object arg) {
            if ((this.DownloadBarCodeCancelCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCodeCancelCompleted(this, new DownloadBarCodeCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCodeFlag", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCodeFlag(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCodeFlag", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            ReturnDescription = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCodeFlagAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.DownloadBarCodeFlagAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCodeFlagAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.DownloadBarCodeFlagOperationCompleted == null)) {
                this.DownloadBarCodeFlagOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCodeFlagOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCodeFlag", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.DownloadBarCodeFlagOperationCompleted, userState);
        }
        
        private void OnDownloadBarCodeFlagOperationCompleted(object arg) {
            if ((this.DownloadBarCodeFlagCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCodeFlagCompleted(this, new DownloadBarCodeFlagCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RefuseDownloadBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool RefuseDownloadBarCode(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out string ReturnDescription) {
            object[] results = this.Invoke("RefuseDownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            ReturnDescription = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void RefuseDownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.RefuseDownloadBarCodeAsync(DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void RefuseDownloadBarCodeAsync(string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.RefuseDownloadBarCodeOperationCompleted == null)) {
                this.RefuseDownloadBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRefuseDownloadBarCodeOperationCompleted);
            }
            this.InvokeAsync("RefuseDownloadBarCode", new object[] {
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.RefuseDownloadBarCodeOperationCompleted, userState);
        }
        
        private void OnRefuseDownloadBarCodeOperationCompleted(object arg) {
            if ((this.RefuseDownloadBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RefuseDownloadBarCodeCompleted(this, new RefuseDownloadBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DownloadBarCode_yz", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DownloadBarCode_yz(string SourceOrgID, string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, out System.Xml.XmlNode nodeBarCode, out System.Xml.XmlNode nodeNRequestItem, out System.Xml.XmlNode nodeNRequestForm, out string xmlWebLisOthers, out string ReturnDescription) {
            object[] results = this.Invoke("DownloadBarCode_yz", new object[] {
                        SourceOrgID,
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser});
            nodeBarCode = ((System.Xml.XmlNode)(results[1]));
            nodeNRequestItem = ((System.Xml.XmlNode)(results[2]));
            nodeNRequestForm = ((System.Xml.XmlNode)(results[3]));
            xmlWebLisOthers = ((string)(results[4]));
            ReturnDescription = ((string)(results[5]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadBarCode_yzAsync(string SourceOrgID, string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser) {
            this.DownloadBarCode_yzAsync(SourceOrgID, DestiOrgID, BarCodeNo, WebLiser, null);
        }
        
        /// <remarks/>
        public void DownloadBarCode_yzAsync(string SourceOrgID, string DestiOrgID, string BarCodeNo, System.Xml.XmlNode WebLiser, object userState) {
            if ((this.DownloadBarCode_yzOperationCompleted == null)) {
                this.DownloadBarCode_yzOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadBarCode_yzOperationCompleted);
            }
            this.InvokeAsync("DownloadBarCode_yz", new object[] {
                        SourceOrgID,
                        DestiOrgID,
                        BarCodeNo,
                        WebLiser}, this.DownloadBarCode_yzOperationCompleted, userState);
        }
        
        private void OnDownloadBarCode_yzOperationCompleted(object arg) {
            if ((this.DownloadBarCode_yzCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadBarCode_yzCompleted(this, new DownloadBarCode_yzCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DownloadBarCodeCompletedEventHandler(object sender, DownloadBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeBarCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeNRequestItem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeNRequestForm {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string xmlWebLisOthers {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DownloadBarCodeStrCompletedEventHandler(object sender, DownloadBarCodeStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCodeStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCodeStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strBarCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strNRequestItem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string strNRequestForm {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string xmlWebLisOthers {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DownloadBarCodeCancelCompletedEventHandler(object sender, DownloadBarCodeCancelCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCodeCancelCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCodeCancelCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DownloadBarCodeFlagCompletedEventHandler(object sender, DownloadBarCodeFlagCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCodeFlagCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCodeFlagCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void RefuseDownloadBarCodeCompletedEventHandler(object sender, RefuseDownloadBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RefuseDownloadBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RefuseDownloadBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DownloadBarCode_yzCompletedEventHandler(object sender, DownloadBarCode_yzCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadBarCode_yzCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadBarCode_yzCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeBarCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeNRequestItem {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public System.Xml.XmlNode nodeNRequestForm {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string xmlWebLisOthers {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string ReturnDescription {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
    }
}

#pragma warning restore 1591