//查看部门员工
Ext.ns('Ext.manage');
Ext.define('Ext.manage.departmentstaff.showyuangongForm', {
    extend: 'Ext.zhifangux.FormPanel',
    alias: 'widget.showyuangongForm',
    title: '员工基本信息',
    defaultTitle: '员工基本信息',
    width: 434,
    height: 443,
    objectName: 'HREmployee',
    addUrl: 'RBACService.svc/RBAC_UDTO_AddHREmployee',
    editUrl: 'RBACService.svc/RBAC_UDTO_UpdateHREmployeeByField',
    selectUrl: 'RBACService.svc/RBAC_UDTO_SearchHREmployeeById',
    type: 'show',
    initComponent: function() {
        var me = this;
        if (me.type == 'show') {
            me.height -= 25;
        }
        me.fields = 'HREmployee_NameL,HREmployee_NameF,HREmployee_CName,HREmployee_PinYinZiTou,HREmployee_EName,HREmployee_IdNumber,HREmployee_Shortcode,HREmployee_BSex_Id,HREmployee_Birthday,HREmployee_UseCode,HREmployee_HRDept_Id,HREmployee_HRPosition_Id,HREmployee_JobDuty,HREmployee_IsEnabled,HREmployee_MobileTel,HREmployee_OfficeTel,HREmployee_ExtTel,HREmployee_Email,HREmployee_Comment,HREmployee_LabID,HREmployee_Id,HREmployee_HRDept_DataTimeStamp,HREmployee_HRPosition_DataTimeStamp,HREmployee_BSex_DataTimeStamp,HREmployee_DataTimeStamp';
        me.items = [{
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_NameL',
            name: 'HREmployee_NameL',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 12,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '姓',
            labelAlign: 'right',
            sortNum: 1,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_NameF',
            name: 'HREmployee_NameF',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 38,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '名',
            labelAlign: 'right',
            sortNum: 2,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_CName',
            name: 'HREmployee_CName',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 64,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '名称',
            labelAlign: 'right',
            sortNum: 3,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_PinYinZiTou',
            name: 'HREmployee_PinYinZiTou',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 90,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '拼音字头',
            labelAlign: 'right',
            sortNum: 4,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_EName',
            name: 'HREmployee_EName',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 116,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '英文名称',
            labelAlign: 'right',
            sortNum: 5,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_IdNumber',
            name: 'HREmployee_IdNumber',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 142,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '身份证号',
            labelAlign: 'right',
            sortNum: 26,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_Shortcode',
            name: 'HREmployee_Shortcode',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 4,
            y: 167,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '快捷码',
            labelAlign: 'right',
            sortNum: 6,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },{
            xtype: 'combobox',
            editable: true,
            typeAhead: true,
            queryMode: 'local',
            defaultValue: '',
            displayField: 'BSex_Name',
            valueField: 'BSex_Id',
            DataTimeStampField: 'HREmployee_BSex_DataTimeStamp',
            store: me.createComboStore({
                fields: 'BSex_Name,BSex_Id,BSex_DataTimeStamp',
                url: 'SingleTableService.svc/ST_UDTO_SearchBSexByHQL?isPlanish=true',
                InteractionField: 'HREmployee_BSex_Id',
                DataTimeStampField: 'HREmployee_BSex_DataTimeStamp',
                valueField: 'BSex_Id'
            }),
            type: 'combobox',
            itemId: 'HREmployee_BSex_Id',
            name: 'HREmployee_BSex_Id',
            labelWidth: 60,
            height: 22,
            x: 5,
            y: 195,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '性别',
            labelAlign: 'right',
            sortNum: 7,
            hasReadOnly: false,
            hidden: false,
            width: 200,
            listeners: me.createComboListeners()
        },
        Ext.create('Ext.zhifangux.DateField', {
            editable: false,
            format: 'Y-m-d',
            type: 'datefield',
            itemId: 'HREmployee_Birthday',
            name: 'HREmployee_Birthday',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 220,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '出生日期',
            labelAlign: 'right',
            sortNum: 8,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        }), {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_UseCode',
            name: 'HREmployee_UseCode',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 12,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '代码',
            labelAlign: 'right',
            sortNum: 9,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'combobox',
            hasButton: true,
            mode: 'local',
            editable: false,
            displayField: 'text',
            valueField: 'value',
            store: new Ext.data.SimpleStore({
                fields: ['value', 'text'],
                data: []
            }),
            type: 'datacombobox',
            itemId: 'HREmployee_HRDept_Id',
            name: 'HREmployee_HRDept_Id',
            labelWidth: 60,
            width: 177,
            height: 22,
            x: 210,
            y: 38,
            readOnly: true,
            labelStyle: 'font-style:normal',
            fieldLabel: '部门',
            labelAlign: 'right',
            sortNum: 10,
            hasReadOnly: true,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'button',
            width: 22,
            height: 22,
            itemId: 'HREmployeeHRDeptId.FunctionBtn',
            name: 'HREmployeeHRDeptId.FunctionBtn',
            disabled: true,
            x: 385,
            y: 38,
            boundField: 'HREmployee_HRDept_Id',
            appComID: '5326294945188498462',
            iconCls: 'build-button-configuration-blue',
            margin: '0 0 0 2',
            listeners: {
                click: function(com, e, op) {
                    me.funBtnClick(com);
                }
            }
        },
        {
            xtype: 'combobox',
            editable: true,
            typeAhead: true,
            queryMode: 'local',
            defaultValue: '4853804804950822271',
            displayField: 'HRPosition_CName',
            valueField: 'HRPosition_Id',
            DataTimeStampField: 'HREmployee_HRPosition_DataTimeStamp',
            store: me.createComboStore({
                fields: 'HRPosition_CName,HRPosition_Id,HRPosition_DataTimeStamp',
                url: 'RBACService.svc/RBAC_UDTO_SearchHRPositionByHQL?isPlanish=true',
                InteractionField: 'HREmployee_HRPosition_Id',
                DataTimeStampField: 'HREmployee_HRPosition_DataTimeStamp',
                valueField: 'HRPosition_Id'
            }),
            type: 'combobox',
            itemId: 'HREmployee_HRPosition_Id',
            name: 'HREmployee_HRPosition_Id',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 64,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '职位',
            labelAlign: 'right',
            sortNum: 12,
            hasReadOnly: false,
            hidden: false,
            value: '4853804804950822271',
            listeners: me.createComboListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_JobDuty',
            name: 'HREmployee_JobDuty',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 90,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '工作职责',
            labelAlign: 'right',
            sortNum: 13,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'combobox',
            hasButton: false,
            mode: 'local',
            editable: false,
            displayField: 'text',
            valueField: 'value',
            store: new Ext.data.SimpleStore({
                fields: ['value', 'text'],
                data: [['1', '是'], ['0', '否']]
            }),
            type: 'datacombobox',
            itemId: 'HREmployee_IsEnabled',
            name: 'HREmployee_IsEnabled',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 116,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '在职',
            labelAlign: 'right',
            sortNum: 14,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_MobileTel',
            name: 'HREmployee_MobileTel',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 142,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '手机号码',
            labelAlign: 'right',
            sortNum: 15,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_OfficeTel',
            name: 'HREmployee_OfficeTel',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 168,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '办公电话',
            labelAlign: 'right',
            sortNum: 16,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_ExtTel',
            name: 'HREmployee_ExtTel',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 194,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '分机',
            labelAlign: 'right',
            sortNum: 17,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_Email',
            name: 'HREmployee_Email',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 220,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: 'Email',
            labelAlign: 'right',
            sortNum: 18,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textarea',
            type: 'textareafield',
            itemId: 'HREmployee_Comment',
            name: 'HREmployee_Comment',
            labelWidth: 60,
            width: 405,
            height: 44,
            x: 5,
            y: 246,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '描述',
            labelAlign: 'right',
            sortNum: 19,
            hasReadOnly: false,
            hidden: false,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_LabID',
            name: 'HREmployee_LabID',
            labelWidth: 60,
            width: 160,
            height: 22,
            x: 5,
            y: 186,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '实验室ID',
            labelAlign: 'right',
            sortNum: 20,
            hasReadOnly: false,
            hidden: true,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_Id',
            name: 'HREmployee_Id',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 187,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '主键ID',
            labelAlign: 'right',
            sortNum: 21,
            hasReadOnly: false,
            hidden: true,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_HRDept_DataTimeStamp',
            name: 'HREmployee_HRDept_DataTimeStamp',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 187,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '部门时间戳',
            labelAlign: 'right',
            sortNum: 22,
            hasReadOnly: false,
            hidden: true,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_HRPosition_DataTimeStamp',
            name: 'HREmployee_HRPosition_DataTimeStamp',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 5,
            y: 0,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '时间戳',
            labelAlign: 'right',
            sortNum: 23,
            hasReadOnly: false,
            hidden: true,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_BSex_DataTimeStamp',
            name: 'HREmployee_BSex_DataTimeStamp',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 117,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '时间戳',
            labelAlign: 'right',
            sortNum: 24,
            hasReadOnly: false,
            hidden: true,
            listeners: me.createBasicListeners()
        },
        {
            xtype: 'textfield',
            type: 'textfield',
            itemId: 'HREmployee_DataTimeStamp',
            name: 'HREmployee_DataTimeStamp',
            labelWidth: 60,
            width: 200,
            height: 22,
            x: 210,
            y: 5,
            readOnly: false,
            labelStyle: 'font-style:normal',
            fieldLabel: '时间戳',
            labelAlign: 'right',
            sortNum: 25,
            hasReadOnly: false,
            hidden: true,
            listeners: me.createBasicListeners()
        }];
        me.dockedItems = [{
            xtype: 'toolbar',
            dock: 'bottom',
            itemId: 'bottomtoolbar',
            items: ['->', {
                xtype: 'button',
                text: '保存',
                iconCls: 'build-button-save',
                handler: function(but) {
                    me.submit();
                }
            },
            {
                xtype: 'button',
                text: '重置',
                iconCls: 'build-button-refresh',
                handler: function(but) {
                    me.getForm().reset();
                }
            }]
        }];
        me.changeConfig();
        me.callParent(arguments);
    }
});