[{
	"title":"如何使用“报告查询”功能？",
	"list":[{
		"title":"第一步",
		"text":"打开就诊人维护界面，开始维护就诊人信息；",
		"img":"personlist.jpg"
	},{
		"title":"第二步",
		"text":"点击上述的“新增就诊人”按钮，开始维护就诊人及就诊医院信息，输入姓名、手机号，输入就诊医院的病历号或就诊卡完成维护工作；",
		"img":"personhospitalid.jpg"
	},{
		"title":"第三步",
		"text":"打开“报告查询”功能；",
		"img":"openreportsearch.jpg"
	},{
		"title":"第四步",
		"text":"进入报告查询界面，点击某个就诊人信息；",
		"img":"reportsearch.jpg"
	},{
		"title":"第五步",
		"text":"点击具体某个检验报告查看；",
		"img":"report.jpg"
	}]
},{
	"title":"如何使用“扫一扫”功能？",
	"list":[{
		"title":"第一步:",
		"text":"打开就诊人维护界面，开始维护就诊人信息；",
		"img":"personlist.jpg"
	},{
		"title":"第二步",
		"text":"点击上述的“新增就诊人”按钮，开始维护就诊人及就诊医院信息，输入姓名、手机号，输入就诊医院的病历号或就诊卡完成维护工作；",
		"img":"personhospitalid.jpg"
	},{
		"title":"第三步",
		"text":"打开“扫一扫”功能；",
		"img":"openscan.jpg"
	},{
		"title":"第四步",
		"text":"进入“扫一扫”功能界面，点开“扫一扫”图标；；",
		"img":"scanlist.jpg"
	},{
		"title":"第五步",
		"text":"扫描用于取用报告单的“条码号”；",
		"img":"scanbarcode.jpg"
	}]
},{
	"title":"如何删除就诊人？",
	"list":[{
		"title":"步骤",
		"text":"点击“删除就诊人”按钮，选择某一就诊人，点击叉号完成删除操作（可能删掉相关联的就诊医院信息）。再次点击“删除就诊人”，恢复页面；",
		"img":"deleteperson.jpg"
	}]
},{
	"title":"如何删除就诊医院信息？",
	"list":[{
		"title":"步骤",
		"text":"点击红色减号，多条就诊医院信息会显示出来，选择一条，点击叉号删除，最后点击保存完成删除操作；",
		"img":"deletehospitalid.jpg"
	}]
},{
	"title":"在账号维护中，设置登录开启后，如何登录？",
	"list":[{
		"title":"步骤",
		"text":"在账号维护中，如果设置了登录开启，则需要输入系统默认设置的密码8888登录",
		"img":"login1.jpg"
	}]
},{
	"title":"如何修改密码？",
	"list":[{
		"title":"步骤",
		"text":"在账号维护——修改密码中，可以修改您的登录密码（注意：未修改之前的密码系统默认为8888）",
		"img":"editcode.jpg"
	}]
}]