//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ZhiFang.WebLis.SingleLogin {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SingleLoginWSSoap", Namespace="http://tempuri.org/")]
    public partial class SingleLoginWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetXMLToMergeCWAndWeblisModulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMergeCWAndWeblisModulesXMLOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SingleLoginWS() {
            this.Url = global::ZhiFang.WebLis.Properties.Settings.Default.ZhiFang_WebLis_SingleLogin_SingleLoginWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetXMLToMergeCWAndWeblisModulesCompletedEventHandler GetXMLToMergeCWAndWeblisModulesCompleted;
        
        /// <remarks/>
        public event GetMergeCWAndWeblisModulesXMLCompletedEventHandler GetMergeCWAndWeblisModulesXMLCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetXMLToMergeCWAndWeblisModules", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetXMLToMergeCWAndWeblisModules(string strUserName, string strPwd, string strXML, out string strDesc, out string strUserID) {
            object[] results = this.Invoke("GetXMLToMergeCWAndWeblisModules", new object[] {
                        strUserName,
                        strPwd,
                        strXML});
            strDesc = ((string)(results[1]));
            strUserID = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetXMLToMergeCWAndWeblisModulesAsync(string strUserName, string strPwd, string strXML) {
            this.GetXMLToMergeCWAndWeblisModulesAsync(strUserName, strPwd, strXML, null);
        }
        
        /// <remarks/>
        public void GetXMLToMergeCWAndWeblisModulesAsync(string strUserName, string strPwd, string strXML, object userState) {
            if ((this.GetXMLToMergeCWAndWeblisModulesOperationCompleted == null)) {
                this.GetXMLToMergeCWAndWeblisModulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetXMLToMergeCWAndWeblisModulesOperationCompleted);
            }
            this.InvokeAsync("GetXMLToMergeCWAndWeblisModules", new object[] {
                        strUserName,
                        strPwd,
                        strXML}, this.GetXMLToMergeCWAndWeblisModulesOperationCompleted, userState);
        }
        
        private void OnGetXMLToMergeCWAndWeblisModulesOperationCompleted(object arg) {
            if ((this.GetXMLToMergeCWAndWeblisModulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetXMLToMergeCWAndWeblisModulesCompleted(this, new GetXMLToMergeCWAndWeblisModulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMergeCWAndWeblisModulesXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMergeCWAndWeblisModulesXML(string strUserName, string strPwd, string strXML, out string strDesc, out string strUserID) {
            object[] results = this.Invoke("GetMergeCWAndWeblisModulesXML", new object[] {
                        strUserName,
                        strPwd,
                        strXML});
            strDesc = ((string)(results[1]));
            strUserID = ((string)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMergeCWAndWeblisModulesXMLAsync(string strUserName, string strPwd, string strXML) {
            this.GetMergeCWAndWeblisModulesXMLAsync(strUserName, strPwd, strXML, null);
        }
        
        /// <remarks/>
        public void GetMergeCWAndWeblisModulesXMLAsync(string strUserName, string strPwd, string strXML, object userState) {
            if ((this.GetMergeCWAndWeblisModulesXMLOperationCompleted == null)) {
                this.GetMergeCWAndWeblisModulesXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMergeCWAndWeblisModulesXMLOperationCompleted);
            }
            this.InvokeAsync("GetMergeCWAndWeblisModulesXML", new object[] {
                        strUserName,
                        strPwd,
                        strXML}, this.GetMergeCWAndWeblisModulesXMLOperationCompleted, userState);
        }
        
        private void OnGetMergeCWAndWeblisModulesXMLOperationCompleted(object arg) {
            if ((this.GetMergeCWAndWeblisModulesXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMergeCWAndWeblisModulesXMLCompleted(this, new GetMergeCWAndWeblisModulesXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetXMLToMergeCWAndWeblisModulesCompletedEventHandler(object sender, GetXMLToMergeCWAndWeblisModulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetXMLToMergeCWAndWeblisModulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetXMLToMergeCWAndWeblisModulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strDesc {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strUserID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void GetMergeCWAndWeblisModulesXMLCompletedEventHandler(object sender, GetMergeCWAndWeblisModulesXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMergeCWAndWeblisModulesXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMergeCWAndWeblisModulesXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strDesc {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string strUserID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591