using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Web;
using System.IO;
using ZhiFang.ServiceCommon.RBAC;
using ZhiFang.Entity.Base;
using ZhiFang.Entity.ReagentSys.Client;

namespace ZhiFang.ReagentSys.Client.ServerContract
{
    [ServiceContract]
    public interface IReaStatisticalAnalysisService
    {
        //[ServiceContractDescription(Name = "入库统计", Desc = "入库统计", Url = "ReaStatisticalAnalysisService.svc/StatisticalAnalysisBmsInDocByGoodsNo", Get = "", Post = "", Return = "BaseResultDataValue", ReturnType = "StatisticalAnalysisBmsInDocVOList")]
        //[WebInvoke(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/StatisticalAnalysisBmsInDocByGoodsNo", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        //[OperationContract]
        //BaseResultDataValue StatisticalAnalysisBmsInDocByGoodsNo(string StartDate, string EndDate, string CenOrgIdList, string GoodsNoList, string ComOrgIdList, string BmsInDocTypeList, string DateType, string CenOrgLevel);

        #region 统计查询
        [ServiceContractDescription(Name = "获取订单明细汇总统计报表", Desc = "获取订单明细汇总统计报表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaBmsCenOrderDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Get = "groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Post = "", Return = "BaseResultList<ReaBmsCenOrderDtl>", ReturnType = "ListReaBmsCenOrderDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaBmsCenOrderDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaBmsCenOrderDtlSummaryByHQL(int groupType, string docHql, string dtlHql, string reaGoodsHql, string fields, bool isPlanish, string sort, int page, int limit);

        [ServiceContractDescription(Name = "获取供货明细汇总统计报表", Desc = "获取供货明细汇总统计报表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaBmsCenSaleDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Get = "groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Post = "", Return = "BaseResultList<ReaBmsCenOrderDtl>", ReturnType = "ListReaBmsCenOrderDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaBmsCenSaleDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaBmsCenSaleDtlSummaryByHQL(int groupType, string docHql, string dtlHql, string reaGoodsHql, string fields, bool isPlanish, string sort, int page, int limit);

        [ServiceContractDescription(Name = "获取入库明细汇总统计报表", Desc = "获取入库明细汇总统计报表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaBmsInDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}&isOfColdInfoMerge={isOfColdInfoMerge}", Get = "groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}&isOfColdInfoMerge={isOfColdInfoMerge}", Post = "", Return = "BaseResultList<ReaBmsInDtl>", ReturnType = "ListReaBmsInDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaBmsInDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}&isOfColdInfoMerge={isOfColdInfoMerge}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaBmsInDtlSummaryByHQL(int groupType, string docHql, string dtlHql, string reaGoodsHql, string fields, bool isPlanish, string sort, int page, int limit, bool isOfColdInfoMerge);

        [ServiceContractDescription(Name = "获取移库领用明细统计报表", Desc = "获取移库领用明细统计报表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchTransferDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Get = "groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Post = "", Return = "BaseResultList<ReaBmsTransferDtl>", ReturnType = "ListReaBmsTransferDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchTransferDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchTransferDtlSummaryByHQL(int groupType, string docHql, string dtlHql, string reaGoodsHql, string fields, bool isPlanish, string sort, int page, int limit);

        [ServiceContractDescription(Name = "获取出库明细汇总统计报表", Desc = "获取出库明细汇总统计报表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaBmsOutDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Get = "groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Post = "", Return = "BaseResultList<ReaBmsOutDtl>", ReturnType = "ListReaBmsOutDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaBmsOutDtlSummaryByHQL?groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaBmsOutDtlSummaryByHQL(int groupType, string docHql, string dtlHql, string reaGoodsHql, string fields, bool isPlanish, string sort, int page, int limit);

        [ServiceContractDescription(Name = "按机构货品的最大包装单位试剂耗材信息进行综合统计报表", Desc = "按机构货品的最大包装单位试剂耗材信息进行综合统计报表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyEntityListHQL?groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Get = "groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Post = "", Return = "BaseResultList<ReaBmsOutDtl>", ReturnType = "ListReaBmsOutDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyEntityListHQL?groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyEntityListHQL(int groupType, string companyId, string deptId, string testEquipId, string reaGoodsNo, string startDate, string endDate, string fields, bool isPlanish, string sort, int page, int limit);

        [ServiceContractDescription(Name = "获取移库领用及使用返回统计", Desc = "获取移库领用及使用返回统计", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaTransferAndOutDtlVOListByHQL?groupType={groupType}&hqlStr={hqlStr}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Get = "groupType={groupType}&hqlStr={hqlStr}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Post = "", Return = "BaseResultList<ReaBmsOutDtl>", ReturnType = "ListReaBmsOutDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaTransferAndOutDtlVOListByHQL?groupType={groupType}&hqlStr={hqlStr}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaTransferAndOutDtlVOListByHQL(int groupType, string hqlStr, string fields, bool isPlanish, string sort, int page, int limit);

        [ServiceContractDescription(Name = "获取出库变更台账统计", Desc = "获取出库变更台账统计", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaBmsOutDtlLotNoAndTransportNoChangeByHQL?docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Get = "docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", Post = "", Return = "BaseResultList<ReaBmsOutDtl>", ReturnType = "ListReaBmsOutDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaBmsOutDtlLotNoAndTransportNoChangeByHQL?docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&isPlanish={isPlanish}&sort={sort}&page={page}&limit={limit}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaBmsOutDtlLotNoAndTransportNoChangeByHQL(string docHql, string dtlHql, string reaGoodsHql, string fields, bool isPlanish, string sort, int page, int limit);
        #endregion

        #region Excel导出/PDF预览
        [ServiceContractDescription(Name = "将各业务汇总统计报表按Excel模板导出Excel文件", Desc = "将各业务汇总统计报表按Excel模板导出Excel文件", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchBusinessSummaryReportOfExcelByHql?operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&sort={sort}&startDate={startDate}&endDate={endDate}&isOfColdInfoMerge={isOfColdInfoMerge}", Get = "operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&sort={sort}&startDate={startDate}&endDate={endDate}&isOfColdInfoMerge={isOfColdInfoMerge}", Post = "", Return = "Stream", ReturnType = "Stream")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchBusinessSummaryReportOfExcelByHql?operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&sort={sort}&startDate={startDate}&endDate={endDate}&isOfColdInfoMerge={isOfColdInfoMerge}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        Stream RS_UDTO_SearchBusinessSummaryReportOfExcelByHql(long operateType, string breportType, string frx, int groupType, string docHql, string dtlHql, string reaGoodsHql, string sort, string startDate, string endDate, bool isOfColdInfoMerge);

        [ServiceContractDescription(Name = "按机构货品的最大包装单位试剂耗材信息进行综合统计报表,导出Excel文件", Desc = "按机构货品的最大包装单位试剂耗材信息进行综合统计报表,导出Excel文件", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyReportOfExcelByHql?operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&sort={sort}", Get = "operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&sort={sort}", Post = "", Return = "Stream", ReturnType = "Stream")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyReportOfExcelByHql?operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&sort={sort}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        Stream RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyReportOfExcelByHql(long operateType, string breportType, string frx, int groupType, string companyId, string deptId, string testEquipId, string reaGoodsNo, string startDate, string endDate, string sort);

        [ServiceContractDescription(Name = "将各业务汇总统计报表按Excel/Frx模板导出PDF文件", Desc = "将各业务汇总统计报表按Excel/Frx模板导出PDF文件", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchBusinessSummaryReportOfPdfByHql?reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&sort={sort}&startDate={startDate}&endDate={endDate}&isOfColdInfoMerge={isOfColdInfoMerge}", Get = "reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&sort={sort}&startDate={startDate}&endDate={endDate}&isOfColdInfoMerge={isOfColdInfoMerge}", Post = "", Return = "Stream", ReturnType = "Stream")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchBusinessSummaryReportOfPdfByHql?reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&docHql={docHql}&dtlHql={dtlHql}&reaGoodsHql={reaGoodsHql}&sort={sort}&startDate={startDate}&endDate={endDate}&isOfColdInfoMerge={isOfColdInfoMerge}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        Stream RS_UDTO_SearchBusinessSummaryReportOfPdfByHql(string reaReportClass, long operateType, string breportType, string frx, int groupType, string docHql, string dtlHql, string reaGoodsHql, string sort, string startDate, string endDate, bool isOfColdInfoMerge);

        [ServiceContractDescription(Name = "按机构货品的最大包装单位试剂耗材信息进行综合统计报表,导出PDF文件", Desc = "按机构货品的最大包装单位试剂耗材信息进行综合统计报表,导出PDF文件", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyReportOfPdfByHql?reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&sort={sort}", Get = "reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&sort={sort}}", Post = "", Return = "Stream", ReturnType = "Stream")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyReportOfPdfByHql?reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&companyId={companyId}&deptId={deptId}&testEquipId={testEquipId}&reaGoodsNo={reaGoodsNo}&startDate={startDate}&endDate={endDate}&sort={sort}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        Stream RS_UDTO_SearchReaGoodsStatisticsOfMaxGonvertQtyReportOfPdfByHql(string reaReportClass, long operateType, string breportType, string frx, int groupType, string companyId, string deptId, string testEquipId, string reaGoodsNo, string startDate, string endDate, string sort);

        [ServiceContractDescription(Name = "移库领用及使用返回统计按Excel模板导出Excel文件", Desc = "移库领用及使用返回统计按Excel模板导出Excel文件", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaTransferAndOutDtlVOOfExcelByHql?operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&hqlStr={hqlStr}&sort={sort}", Get = "operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&hqlStr={hqlStr}&sort={sort}", Post = "", Return = "Stream", ReturnType = "Stream")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaTransferAndOutDtlVOOfExcelByHql?operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&hqlStr={hqlStr}&sort={sort}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        Stream RS_UDTO_SearchReaTransferAndOutDtlVOOfExcelByHql(long operateType, string breportType, string frx, int groupType, string hqlStr, string sort);

        [ServiceContractDescription(Name = "移库领用及使用返回统计按Excel/Frx模板导出PDF文件", Desc = "移库领用及使用返回统计按Excel/Frx模板导出PDF文件", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaTransferAndOutDtlVOOfPdfByHql?reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&hqlStr={hqlStr}&sort={sort}", Get = "reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&hqlStr={hqlStr}&sort={sort}", Post = "", Return = "Stream", ReturnType = "Stream")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaTransferAndOutDtlVOOfPdfByHql?reaReportClass={reaReportClass}&operateType={operateType}&breportType={breportType}&frx={frx}&groupType={groupType}&hqlStr={hqlStr}&sort={sort}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        Stream RS_UDTO_SearchReaTransferAndOutDtlVOOfPdfByHql(string reaReportClass, long operateType, string breportType, string frx, int groupType, string hqlStr, string sort);

        #endregion

        #region 消耗比对分析

        [ServiceContractDescription(Name = "消耗比对分析,获取仪器试剂使用量", Desc = "消耗比对分析,获取仪器试剂使用量", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchReaBmsOutDtEntityListByJoinHql?groupType={groupType}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&page={page}&limit={limit}&sort={sort}&isPlanish={isPlanish}", Get = "groupType={groupType}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&page={page}&limit={limit}&sort={sort}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<ReaBmsOutDtl>", ReturnType = "ListReaBmsOutDtl")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchReaBmsOutDtEntityListByJoinHql?groupType={groupType}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&page={page}&limit={limit}&sort={sort}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchReaBmsOutDtEntityListByJoinHql(int groupType, string startDate, string endDate, string docHql, string dtlHql, string deptGoodsHql, string reaGoodsHql, string fields, int page, int limit, string sort, bool isPlanish);

        [ServiceContractDescription(Name = "消耗比对分析,项目检测量", Desc = "消耗比对分析,项目检测量", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchTestStatisticalResultsListByJoinHql?groupType={groupType}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&fields={fields}&page={page}&limit={limit}&sort={sort}&isPlanish={isPlanish}", Get = "groupType={groupType}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&fields={fields}&page={page}&limit={limit}&sort={sort}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<ReaLisTestStatisticalResults>", ReturnType = "ListReaLisTestStatisticalResults")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchTestStatisticalResultsListByJoinHql?groupType={groupType}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&fields={fields}&page={page}&limit={limit}&sort={sort}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchTestStatisticalResultsListByJoinHql(int groupType, string startDate, string endDate, string dtlHql, string fields, int page, int limit, string sort, bool isPlanish);

        [ServiceContractDescription(Name = "消耗比对分析,试剂理论消耗量/消耗比对分析", Desc = "消耗比对分析,试剂理论消耗量/消耗比对分析", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchConsumptionComparisonAnalysisVOListByHql?groupType={groupType}&statisticType={statisticType}&startDate={startDate}&endDate={endDate}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&page={page}&limit={limit}&sortType={sortType}&isPlanish={isPlanish}&isMergeOfItem={isMergeOfItem}", Get = "groupType={groupType}&statisticType={statisticType}&startDate={startDate}&endDate={endDate}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&page={page}&limit={limit}&sortType={sortType}&isPlanish={isPlanish}&isMergeOfItem={isMergeOfItem}", Post = "", Return = "BaseResultList<ConsumptionComparisonAnalysisVO>", ReturnType = "ListConsumptionComparisonAnalysisVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchConsumptionComparisonAnalysisVOListByHql?groupType={groupType}&statisticType={statisticType}&startDate={startDate}&endDate={endDate}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&page={page}&limit={limit}&sortType={sortType}&isPlanish={isPlanish}&isMergeOfItem={isMergeOfItem}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchConsumptionComparisonAnalysisVOListByHql(int groupType, int statisticType, string startDate, string endDate, string equipIdStr, string goodsIdStr, string fields, int page, int limit, string sortType, bool isPlanish, bool isMergeOfItem);

        #endregion

        #region ECharts图表统计

        [ServiceContractDescription(Name = "ECharts(堆叠)统计服务", Desc = "ECharts(堆叠)统计服务", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchStackEChartsVOListByHql?statisticType={statisticType}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}", Get = "statisticType={statisticType}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchStackEChartsVOListByHql?statisticType={statisticType}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchStackEChartsVOListByHql(int statisticType, string startDate, string endDate, string docHql, string dtlHql, string deptGoodsHql, string reaGoodsHql);

        [ServiceContractDescription(Name = "ECharts(按库房/按供货商/按品牌/按货品分类)入库统计", Desc = "ECharts(按库房/按供货商/按品牌/按货品分类)入库统计", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchInEChartsVOListByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Get = "statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchInEChartsVOListByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchInEChartsVOListByHql(int statisticType, bool showZero, string startDate, string endDate, string docHql, string dtlHql, string deptGoodsHql, string reaGoodsHql, string fields, string sort, bool isPlanish);

        [ServiceContractDescription(Name = "ECharts(按库房/按供货商/按品牌/按货品分类)库存统计", Desc = "ECharts(按库房/按供货商/按品牌/按货品分类)库存统计", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchStockEChartsVOListByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Get = "statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchStockEChartsVOListByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchStockEChartsVOListByHql(int statisticType, bool showZero, string startDate, string endDate, string dtlHql, string deptGoodsHql, string reaGoodsHql, string fields, string sort, bool isPlanish);

        [ServiceContractDescription(Name = "ECharts(按库房/按供货商/按品牌/按货品分类)出库统计", Desc = "ECharts(按库房/按供货商/按品牌/按货品分类)出库统计", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchOutEChartsVOListByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Get = "statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchOutEChartsVOListByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchOutEChartsVOListByHql(int statisticType, bool showZero, string startDate, string endDate, string docHql, string dtlHql, string deptGoodsHql, string reaGoodsHql, string fields, string sort, bool isPlanish);

        [ServiceContractDescription(Name = "消耗比对分析,仪器试剂使用量ECharts图表", Desc = "消耗比对分析,仪器试剂使用量ECharts图表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchEquipReagUsageEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Get = "statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchEquipReagUsageEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&docHql={docHql}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchEquipReagUsageEChartsVOByHql(int statisticType, bool showZero, string startDate, string endDate, string docHql, string dtlHql, string deptGoodsHql, string reaGoodsHql, string fields, string sort, bool isPlanish);

        [ServiceContractDescription(Name = "消耗比对分析,项目检测量ECharts图表", Desc = "消耗比对分析,项目检测量ECharts图表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearchLisResultsEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Get = "statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearchLisResultsEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&deptGoodsHql={deptGoodsHql}&reaGoodsHql={reaGoodsHql}&fields={fields}&sort={sort}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearchLisResultsEChartsVOByHql(int statisticType, bool showZero, string startDate, string endDate, string dtlHql, string deptGoodsHql, string reaGoodsHql, string fields, string sort, bool isPlanish);

        [ServiceContractDescription(Name = "消耗比对分析,试剂理论消耗量ECharts图表", Desc = "消耗比对分析,试剂理论消耗量ECharts图表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearChconsumeTheoryEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&isMergeOfItem={isMergeOfItem}&isPlanish={isPlanish}", Get = "statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&isMergeOfItem={isMergeOfItem}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearChconsumeTheoryEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&isMergeOfItem={isMergeOfItem}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearChconsumeTheoryEChartsVOByHql(int statisticType, bool showZero, string startDate, string endDate, string dtlHql, string equipIdStr, string goodsIdStr, string fields, bool isMergeOfItem, bool isPlanish);

        [ServiceContractDescription(Name = "消耗比对分析,消耗比对分析ECharts图表", Desc = "消耗比对分析,消耗比对分析ECharts图表", Url = "ReaStatisticalAnalysisService.svc/RS_UDTO_SearChconsumeComparisonEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&isMergeOfItem={isMergeOfItem}&isPlanish={isPlanish}", Get = "statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&isMergeOfItem={isMergeOfItem}&isPlanish={isPlanish}", Post = "", Return = "BaseResultList<EChartsVO>", ReturnType = "ListEChartsVO")]
        [WebGet(BodyStyle = WebMessageBodyStyle.WrappedRequest, UriTemplate = "/RS_UDTO_SearChconsumeComparisonEChartsVOByHql?statisticType={statisticType}&showZero={showZero}&startDate={startDate}&endDate={endDate}&dtlHql={dtlHql}&equipIdStr={equipIdStr}&goodsIdStr={goodsIdStr}&fields={fields}&isMergeOfItem={isMergeOfItem}&isPlanish={isPlanish}", RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        BaseResultDataValue RS_UDTO_SearChconsumeComparisonEChartsVOByHql(int statisticType, bool showZero, string startDate, string endDate, string dtlHql, string equipIdStr, string goodsIdStr, string fields, bool isMergeOfItem, bool isPlanish);
        #endregion

    }
}
