
 IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_Module]') AND type in(N'U')) create table RBAC_Module ( LabID bigint null, ModuleID bigint not null, AppComID bigint null, ParentID bigint null, LevelNum int null, TreeCatalog int null, IsLeaf bit null, ModuleType int null, PicFile nvarchar(200) null, URL nvarchar(150) null, Para nvarchar(500) null, Owner varchar(50) null, UseCode varchar(50) null, StandCode varchar(50) null, DeveCode varchar(50) null, CName nvarchar(50) null, EName varchar(50) null, SName varchar(50) null, Shortcode varchar(20) null, PinYinZiTou varchar(50) null, Comment nvarchar(500) null, IsUse bit null, DispOrder int null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, constraint PK_RBAC_MODULE primary key clustered (ModuleID));
 
 IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_Role]') AND type in(N'U')) create table RBAC_Role ( LabID bigint null, RoleID bigint not null, ParentID bigint null, LevelNum int null, TreeCatalog int null, UseCode varchar(50) null, StandCode varchar(50) null, DeveCode varchar(50) null, CName nvarchar(50) null, EName varchar(50) null, SName varchar(50) null, Shortcode varchar(20) null, PinYinZiTou varchar(50) null, Comment ntext null, IsUse bit null, DispOrder int null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, constraint PK_RBAC_ROLE primary key clustered (RoleID));
 
 IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_EmpOptions]') AND type in(N'U')) create table RBAC_EmpOptions ( LabID bigint null, EmpOptionsID bigint not null, EmpID bigint null, DefaultModuleID bigint null, ModuleIconSize int null, NewModuleLookTime datetime null, AllModuleIconSize int null, IsLock bit null, ModuleInfoSize bigint null, NewInfoModuleLookTime datetime null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, constraint PK_RBAC_EMPOPTIONS primary key clustered (EmpOptionsID));
 
 IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_EmpRoles]') AND type in(N'U')) create table RBAC_EmpRoles ( LabID bigint null, EmpRoleID bigint not null, EmpID bigint null, RoleID bigint null, IsUse bit null, DispOrder int null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, Validity varchar(500) null, constraint PK_RBAC_EMPROLES primary key clustered (EmpRoleID));
 
 IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_ModuleOper]') AND type in(N'U')) create table RBAC_ModuleOper ( LabID bigint null, ModuleOperID bigint not null, AppComOperateID bigint null, ModuleID bigint null, RowFilterID bigint null, InvisibleOrDisable int not null, UseCode varchar(50) null, StandCode varchar(50) null, DeveCode varchar(50) null, CName nvarchar(50) null, EName varchar(50) null, SName varchar(50) null, Shortcode varchar(20) null, PinYinZiTou varchar(50) null, Comment ntext null, IsUse bit null, DispOrder int null, DefaultChecked bit null, OperateURL varchar(200) null, RowFilterURL varchar(200) null, RowFilterBase varchar(500) null, FilterCondition varchar(500) null, ColFilterURL varchar(200) null, ColFilterBase varchar(500) null, ColFilterDesc varchar(50) null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, UseRowFilter bit null, PredefinedField ntext null, constraint PK_RBAC_MODULEOPER primary key clustered (ModuleOperID));
 
 IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_RoleModule]') AND type in(N'U')) create table RBAC_RoleModule ( LabID bigint null, ModuleVisiteID bigint not null, ModuleID bigint null, RoleID bigint null, IsUse bit null, DispOrder int null, IsOftenUse int null, IsDefaultOpen int null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, constraint PK_RBAC_ROLEMODULE primary key clustered (ModuleVisiteID));
 
  IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_RoleRight]') AND type in(N'U')) create table RBAC_RoleRight ( LabID bigint null, RightID bigint not null, RoleID bigint null, ModuleOperID bigint null, RowFilterID bigint null, Comment ntext null, IsUse bit null, DispOrder int null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, constraint PK_RBAC_ROLERIGHT primary key clustered (RightID));

  IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RBAC_RowFilter]') AND type in(N'U')) create table RBAC_RowFilter( LabID bigint null, RowFilterID bigint not null, CName nvarchar(50) null, EName varchar(50) null, SName varchar(50) null, RowFilterCondition ntext null, StandCode varchar(50) null, DeveCode varchar(50) null, PinYinZiTou varchar(50) null, Shortcode varchar(20) null, Comment ntext null, IsUse bit null, DispOrder int null, DataAddTime datetime null, DataUpdateTime datetime null, DataTimeStamp timestamp null, RowFilterConstruction varchar(8000) null, constraint PK_RBAC_ROWFILTER primary key clustered (RowFilterID));

IF COL_LENGTH('Department', 'LabID') IS NULL ALTER TABLE Department ADD LabID bigint; 
IF COL_LENGTH('Department', 'DataAddTime') IS NULL ALTER TABLE Department ADD DataAddTime datetime; 
IF COL_LENGTH('Department', 'DataTimeStamp') IS NULL ALTER TABLE Department ADD DataTimeStamp timestamp; 
IF COL_LENGTH('PUser', 'DataAddTime') IS NULL ALTER TABLE PUser ADD DataAddTime datetime;
IF COL_LENGTH('PUser', 'DataTimeStamp') IS NULL ALTER TABLE PUser ADD DataTimeStamp timestamp; 

IF NOT EXISTS(SELECT * FROM B_Parameter WHERE [ParameterID] = 5536111818360502494) INSERT [B_Parameter] ([LabID],[ParameterID],[Name],[SName],[ParaType],[ParaNo],[ParaValue],[ParaDesc],[DispOrder],[IsUse],[IsUserSet],[DataAddTime],[ItemEditInfo]) VALUES ( 0,5536111818360502494,N'HIS调用时按传入信息自动建立科室人员关系',N'HIS',N'CONFIG',N'BL-ISAT-ADDDU-0014',N'1',N'1:是;0:否;',10,1,0,N'2020-04-04 13:02:27',N'{"ItemXType":"radiogroup","ItemDefaultValue":"1","ItemUnit":"","ItemDataSet":"[{''1'':''是''},{''0'':''否''}]"}');

