
IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SC_RecordType]') AND type in(N'U')) CREATE TABLE [dbo].[SC_RecordType]( [LabID] [bigint] NULL, [RecordTypeID] [bigint] NOT NULL, [ContentTypeID] [int] NULL, [CName] [varchar](50) NULL, [TypeCode] [varchar](50) NULL, [SName] [varchar](80) NULL, [ShortCode] [varchar](50) NULL, [PinYinZiTou] [varchar](50) NULL, [DispOrder] [int] NULL, [Description] [ntext] NULL, [BGColor] [varchar](60) NULL, [Memo] [ntext] NULL, [IsUse] [bit] NULL, [DataAddTime] [datetime] NULL, [DataUpdateTime] [datetime] NULL, [DataTimeStamp] [timestamp] NULL, CONSTRAINT [PK_SC_RecordType] PRIMARY KEY NONCLUSTERED( [RecordTypeID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]; 

IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SC_RecordTypeItem]') AND type in(N'U')) CREATE TABLE [dbo].[SC_RecordTypeItem]( [LabID] [bigint] NULL, [RecordTypeItemID] [bigint] NOT NULL, [ItemCode] [varchar](50) NULL, [CName] [varchar](50) NULL, [SName] [varchar](80) NULL, [ShortCode] [varchar](50) NULL, [PinYinZiTou] [varchar](50) NULL, [ItemEditInfo] [ntext] NULL, [DefaultValue] [varchar](100) NULL, [ItemXType] [varchar](100) NULL, [ItemUnit] [varchar](100) NULL, [Description] [ntext] NULL, [BGColor] [varchar](60) NULL, [Memo] [ntext] NULL, [DispOrder] [int] NULL, [IsUse] [bit] NULL, [DataAddTime] [datetime] NULL, [DataUpdateTime] [datetime] NULL, [DataTimeStamp] [timestamp] NULL, CONSTRAINT [PK_SC_RecordTypeItem] PRIMARY KEY NONCLUSTERED( [RecordTypeItemID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]; 

IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SC_RecordItemLink]') AND type in(N'U')) CREATE TABLE [dbo].[SC_RecordItemLink]( [LabID] [bigint] NULL, [RecordLinkId] [bigint] NOT NULL, [RecordTypeID] [bigint] NOT NULL, [RecordTypeItemID] [bigint] NOT NULL, [DispOrder] [int] NULL, [IsUse] [bit] NULL, [DataAddTime] [datetime] NULL, [DataTimeStamp] [timestamp] NULL, CONSTRAINT [PK_SC_RecordItemLink] PRIMARY KEY CLUSTERED( [RecordLinkId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]; 

IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SC_RecordPhrase]') AND type in(N'U')) CREATE TABLE [dbo].[SC_RecordPhrase]( [LabID] [bigint] NULL, [PhraseID] [bigint] NOT NULL, [PhraseType] [bigint] NULL,[TypeObjectId] [bigint] NULL,[BObjectId] [bigint] NULL, [CName] [varchar](80) NULL, [SName] [varchar](80) NULL, [ShortCode] [varchar](40) NULL, [PinYinZiTou] [varchar](50) NULL, [IsUse] [bit] NULL, [Memo] [ntext] NULL, [DispOrder] [int] NULL, [DataAddTime] [datetime] NULL, [DataTimeStamp] [timestamp] NULL, CONSTRAINT [PK_SC_RecordPhrase] PRIMARY KEY NONCLUSTERED( [PhraseID] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]; 

IF EXISTS (SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE CONSTRAINT_NAME = 'FK_SC_RecordItemLink_SC_RecordType') ALTER TABLE [dbo].[SC_RecordItemLink] DROP CONSTRAINT [FK_SC_RecordItemLink_SC_RecordType]; ALTER TABLE [dbo].[SC_RecordItemLink] WITH CHECK ADD CONSTRAINT [FK_SC_RecordItemLink_SC_RecordType] FOREIGN KEY([RecordTypeID]) REFERENCES [dbo].[SC_RecordType]([RecordTypeID]); ALTER TABLE [dbo].[SC_RecordItemLink] CHECK CONSTRAINT [FK_SC_RecordItemLink_SC_RecordType];


IF EXISTS (SELECT * FROM information_schema.KEY_COLUMN_USAGE WHERE CONSTRAINT_NAME = 'FK_SC_RecordItemLink_SC_RecordTypeItem') ALTER TABLE [dbo].[SC_RecordItemLink] DROP CONSTRAINT [FK_SC_RecordItemLink_SC_RecordTypeItem]; ALTER TABLE [dbo].[SC_RecordItemLink] WITH CHECK ADD CONSTRAINT [FK_SC_RecordItemLink_SC_RecordTypeItem] FOREIGN KEY([RecordTypeItemID]) REFERENCES [dbo].[SC_RecordTypeItem]([RecordTypeItemID]); ALTER TABLE [dbo].[SC_RecordItemLink] CHECK CONSTRAINT [FK_SC_RecordItemLink_SC_RecordTypeItem];


IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SC_BarCodeRules]') AND type in(N'U')) CREATE TABLE [dbo].[SC_BarCodeRules]( [LabID] [bigint] NULL, [RulesId] [bigint] NOT NULL, [BmsType] [varchar](60) NULL, [CurBarCode] [bigint] NULL, [DataAddTime] [datetime] NULL, [DataUpdateTime] [datetime] NULL, [DataTimeStamp] [timestamp] NULL, CONSTRAINT [PK_SC_BarCodeRules] PRIMARY KEY CLUSTERED( [RulesId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY]; 

IF NOT EXISTS(SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[B_LodopTemplet]') AND type in(N'U')) CREATE TABLE [dbo].[B_LodopTemplet]( [LabID] [bigint] NOT NULL, [LTId] [bigint] NOT NULL, [CName] [varchar](40) NULL, [TypeCode] [varchar](50) NULL, [TypeCName] [varchar](50) NULL, [PaperType] [varchar](50) NULL, [PrintingDirection] [varchar](50) NULL, [PaperWidth] [float] NULL, [PaperHigh] [float] NULL, [PaperUnit] [varchar](50) NULL, [TemplateCode] [ntext] NULL, [DataTestValue] [ntext] NULL, [DispOrder] [int] NULL, [Memo] [ntext] NULL, [IsUse] [bit] NULL, [DataAddTime] [datetime] NULL, [DataTimeStamp] [timestamp] NULL, CONSTRAINT [PK_B_LODOPTEMPLET] PRIMARY KEY CLUSTERED( [LTId] ASC)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];
