//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ReportFormServiceDemo.ReportFormWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReportFormWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ReportFormWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByReportFormIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByFormNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByPatNoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReportFormWebService() {
            this.Url = global::ReportFormServiceDemo.Properties.Settings.Default.ReportFormServiceDemo_ReportFormWebService_ReportFormWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetReportFormPDFByReportFormIDCompletedEventHandler GetReportFormPDFByReportFormIDCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByFormNoCompletedEventHandler GetReportFormPDFByFormNoCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByBarCodeCompletedEventHandler GetReportFormPDFByBarCodeCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByPatNoCompletedEventHandler GetReportFormPDFByPatNoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByReportFormID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByReportFormID(string ReportFormID, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByReportFormID", new object[] {
                        ReportFormID,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByReportFormIDAsync(string ReportFormID, int RangeDay, int flag) {
            this.GetReportFormPDFByReportFormIDAsync(ReportFormID, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByReportFormIDAsync(string ReportFormID, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByReportFormIDOperationCompleted == null)) {
                this.GetReportFormPDFByReportFormIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByReportFormIDOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByReportFormID", new object[] {
                        ReportFormID,
                        RangeDay,
                        flag}, this.GetReportFormPDFByReportFormIDOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByReportFormIDOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByReportFormIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByReportFormIDCompleted(this, new GetReportFormPDFByReportFormIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByFormNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByFormNo(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByFormNo", new object[] {
                        FormNo,
                        FormNoFormat,
                        SplitChar,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFormNoAsync(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag) {
            this.GetReportFormPDFByFormNoAsync(FormNo, FormNoFormat, SplitChar, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFormNoAsync(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByFormNoOperationCompleted == null)) {
                this.GetReportFormPDFByFormNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByFormNoOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByFormNo", new object[] {
                        FormNo,
                        FormNoFormat,
                        SplitChar,
                        RangeDay,
                        flag}, this.GetReportFormPDFByFormNoOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByFormNoOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByFormNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByFormNoCompleted(this, new GetReportFormPDFByFormNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByBarCode(string BarCode, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByBarCode", new object[] {
                        BarCode,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByBarCodeAsync(string BarCode, int RangeDay, int flag) {
            this.GetReportFormPDFByBarCodeAsync(BarCode, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByBarCodeAsync(string BarCode, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByBarCodeOperationCompleted == null)) {
                this.GetReportFormPDFByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByBarCodeOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByBarCode", new object[] {
                        BarCode,
                        RangeDay,
                        flag}, this.GetReportFormPDFByBarCodeOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByBarCodeOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByBarCodeCompleted(this, new GetReportFormPDFByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByPatNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByPatNo(string PatNo, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByPatNo", new object[] {
                        PatNo,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByPatNoAsync(string PatNo, int RangeDay, int flag) {
            this.GetReportFormPDFByPatNoAsync(PatNo, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByPatNoAsync(string PatNo, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByPatNoOperationCompleted == null)) {
                this.GetReportFormPDFByPatNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByPatNoOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByPatNo", new object[] {
                        PatNo,
                        RangeDay,
                        flag}, this.GetReportFormPDFByPatNoOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByPatNoOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByPatNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByPatNoCompleted(this, new GetReportFormPDFByPatNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetReportFormPDFByReportFormIDCompletedEventHandler(object sender, GetReportFormPDFByReportFormIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByReportFormIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByReportFormIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetReportFormPDFByFormNoCompletedEventHandler(object sender, GetReportFormPDFByFormNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByFormNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByFormNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetReportFormPDFByBarCodeCompletedEventHandler(object sender, GetReportFormPDFByBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetReportFormPDFByPatNoCompletedEventHandler(object sender, GetReportFormPDFByPatNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByPatNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByPatNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591