//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="Service_DongHua_YZRMYY.PUB0015Soap")]
    public interface PUB0015Soap {
        
        // CODEGEN: 命名空间 http://tempuri.org 的元素名称 input1 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DHC.Published.PUB0015.BS.PUB0015.HIPService", ReplyAction="*")]
        ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceResponse HIPService(ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HIPServiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HIPService", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceRequestBody Body;
        
        public HIPServiceRequest() {
        }
        
        public HIPServiceRequest(ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HIPServiceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string input2;
        
        public HIPServiceRequestBody() {
        }
        
        public HIPServiceRequestBody(string input1, string input2) {
            this.input1 = input1;
            this.input2 = input2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HIPServiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HIPServiceResponse", Namespace="http://tempuri.org", Order=0)]
        public ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceResponseBody Body;
        
        public HIPServiceResponse() {
        }
        
        public HIPServiceResponse(ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class HIPServiceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HIPServiceResult;
        
        public HIPServiceResponseBody() {
        }
        
        public HIPServiceResponseBody(string HIPServiceResult) {
            this.HIPServiceResult = HIPServiceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PUB0015SoapChannel : ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.PUB0015Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PUB0015SoapClient : System.ServiceModel.ClientBase<ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.PUB0015Soap>, ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.PUB0015Soap {
        
        public PUB0015SoapClient() {
        }
        
        public PUB0015SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PUB0015SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB0015SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PUB0015SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceResponse ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.PUB0015Soap.HIPService(ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceRequest request) {
            return base.Channel.HIPService(request);
        }
        
        public string HIPService(string input1, string input2) {
            ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceRequest inValue = new ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceRequest();
            inValue.Body = new ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceRequestBody();
            inValue.Body.input1 = input1;
            inValue.Body.input2 = input2;
            ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.HIPServiceResponse retVal = ((ZhiFang.ReagentSys.Client.Service_DongHua_YZRMYY.PUB0015Soap)(this)).HIPService(inValue);
            return retVal.Body.HIPServiceResult;
        }
    }
}
