insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID],[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,1,'1-2S','1个质控结果超过X±2S，为违背此规则，提示警告',1,0,2,0,1)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,2,'1-2.5S','1个质控结果超过X±2.5S，为违背此规则，提示存在随机误差',1,0,2.5,0,1)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,3,'1-3S','1个质控结果超过X±3S，为违背此规则，提示存在随机误差',1,0,3,0,1)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,4,'2-2S','2个连续质控结果同时超过X+2S 或X-2S，为违背此规则，表示存在系统误差',2,0,2,0,1)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,5,'3-1S','3个连续的质控测定结果同时超过X+1S或X-1S，为违背此规则，表示存在系统误差',3,0,1,0,1)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,6,'4-1S','4个连续的质控测定结果同时超过X+1S或X-1S，为违背此规则，表示存在系统误差',4,0,1,0,1)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,7,'R-4S','同批2个质控结果之差值超过4S，为违背此规则，表示存在系统误差',0,0,4,0,2)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,9,'5-X','5个连续的质控结果落在平均数的一侧，为违背此规则，表示存在系统误差',5,0,0,0,4)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,10,'8-X','8个连续的质控结果落在平均数的一侧，为违背此规则，表示存在系统误差',8,0,0,0,4)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,11,'9-X','9个连续的质控结果落在平均数的一侧，为违背此规则，表示存在系统误差',9,0,0,0,4)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,12,'10-X','10个连续的质控结果落在平均数的一侧，为违背此规则，表示存在系统误差',10,0,0,0,4)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,14,'(2 of 3)2S','连续的3个质控结果中,有2个质控结果超过X+2S或X-2S控制限',3,2,2,0,5)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,15,'(3 of 6)2S','连续的6个质控结果中,有3个质控结果超过X+2S或X-2S控制限',6,3,2,0,5)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,16,'12-X','12个连续的质控结果落在平均数的一侧，为违背此规则，表示存在系统误差',12,0,0,0,4)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,17,'7-T','7个连续的质控结果呈现出向上或向下的趋势，为违背此规则',7,0,0,0,3)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,18,'1-1.5S','1个连续的质控测定结果同时超过(平均数)±(1.5倍标准差),为违背此规则',1,0,1.5,0,1)
insert into [LB_QCRuleBase]([LabID] ,[IsDefault],[QCRuleBaseID] ,[QCRuleBaseName],[RuleDesc],[CountN] ,[CountM],[MultX] ,[MultY] ,[RuleType])
  Values(0,1,19,'R-5S','同批两个质控结果之差值超过(5倍标准差),为违背此规则,表示存在随机误差',0,0,5,0,2)
