declare  @LabID bigint
 set @LabID=4845874299822476943

-- delete from LB_Dict where LabID=4845874299822476943

insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+1,'ResultStatus','结果状态','正常（空白）','N','N','','KB','ZCKB','',0,'','',1,1,1)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+2,'ResultStatus','结果状态','偏低 L','L','L','L','L','PD L','',0,'#0000FF','#0000FF',1,1,2)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+3,'ResultStatus','结果状态','偏高 H','H','H','H','H','PG H','',0,'#FF3333','#FF3333',1,1,3)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+4,'ResultStatus','结果状态','异常低 LL','LL','LL','LL','LL','YCD LL','',0,'#FF00FF','#FF00FF',1,1,4)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+5,'ResultStatus','结果状态','异常高 HH','HH','HH','HH','HH','YCG HH','',0,'#FF00FF','#FF00FF',1,1,5)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+6,'ResultStatus','结果状态','无效','U','U','无效','U','WX','',0,'#AA3333','#AA3333',1,1,6)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+7,'ResultStatus','结果状态','警告','E','E','警告','E','JG','',0,'#FF9900','#FF9900',1,1,7)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+8,'ResultStatus','结果状态','异常','ABN','ABN','异常','ABN','YC','',0,'#EE4499','#EE4499',1,1,8)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+9,'ResultStatus','结果状态','阳性','POS','POS','阳性','POS','YX','',0,'#FF0000','#FF0000',1,1,9)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+10,'ResultStatus','结果状态','阴性','NEG','NEG','阴性','NEG','YX','',0,'','',1,1,10)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+12,'ResultStatus','结果状态','弱阳性','LowPOS','LowPOS','弱阳性','LPOS','RYX','',0,'#FF8800','#FF8800',1,1,12)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+13,'ResultStatus','结果状态','A（异常）','A','A','A','A','A','',0,'#EE4499','#EE4499',1,1,13)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+14,'ResultStatus','结果状态','+（阳性）','+','+','+','+',' ','',0,'','',1,1,14)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+15,'ResultStatus','结果状态','-（阴性）','-','-','-','-','-','',0,'','',1,1,15)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+17,'ResultStatus','结果状态','+-（弱阳性）','+-','+-','+-','+-','+-','',0,'#FF8800','#FF8800',1,1,17)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+20,'ResultStatus','结果状态','阳性/正常','POS-N','POS-N','阳性/正常','POSN','YX/ZC','阳性/正常，阳性为正常',0,'','',1,1,20)
insert into LB_Dict([LabID],[DictID],[DictType],[DictTypeName],[CName],[DictCode],[EName],[SName],[Shortcode],[PinYinZiTou],[DictInfo],[ilevel],[ColorValue],[ColorDefault],[IsUse],[IsDefault],[DispOrder])  Values(@LabID,@LabID+22,'ResultStatus','结果状态','阴性/异常','NEG-A','NEG-A','阴性/异常','NEGA','YX/YC','',0,'#FF0000','#FF0000',1,1,22)
