//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace ReportFormServiceDemo.ReportFormWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReportFormWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class ReportFormWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByReportFormIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByFormNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByBarCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByPatNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByZDY17OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateReportPrintTimesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByReportFormID_FTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByFormNo_FTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateReportPrintTimesByFormIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormBitsPDFByPatNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportFormPDFByFields_Base64StringOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReportFormWebService() {
            this.Url = global::ReportFormServiceDemo.Properties.Settings.Default.ReportFormServiceDemo_ReportFormWebService_ReportFormWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetReportFormPDFByReportFormIDCompletedEventHandler GetReportFormPDFByReportFormIDCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByFormNoCompletedEventHandler GetReportFormPDFByFormNoCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByBarCodeCompletedEventHandler GetReportFormPDFByBarCodeCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByPatNoCompletedEventHandler GetReportFormPDFByPatNoCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByZDY17CompletedEventHandler GetReportFormPDFByZDY17Completed;
        
        /// <remarks/>
        public event GetReportFormPDFByFieldsCompletedEventHandler GetReportFormPDFByFieldsCompleted;
        
        /// <remarks/>
        public event UpdateReportPrintTimesCompletedEventHandler UpdateReportPrintTimesCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByReportFormID_FTPCompletedEventHandler GetReportFormPDFByReportFormID_FTPCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByFormNo_FTPCompletedEventHandler GetReportFormPDFByFormNo_FTPCompleted;
        
        /// <remarks/>
        public event UpdateReportPrintTimesByFormIdCompletedEventHandler UpdateReportPrintTimesByFormIdCompleted;
        
        /// <remarks/>
        public event GetReportFormBitsPDFByPatNoCompletedEventHandler GetReportFormBitsPDFByPatNoCompleted;
        
        /// <remarks/>
        public event GetReportFormPDFByFields_Base64StringCompletedEventHandler GetReportFormPDFByFields_Base64StringCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByReportFormID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByReportFormID(string ReportFormID, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByReportFormID", new object[] {
                        ReportFormID,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByReportFormIDAsync(string ReportFormID, int RangeDay, int flag) {
            this.GetReportFormPDFByReportFormIDAsync(ReportFormID, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByReportFormIDAsync(string ReportFormID, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByReportFormIDOperationCompleted == null)) {
                this.GetReportFormPDFByReportFormIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByReportFormIDOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByReportFormID", new object[] {
                        ReportFormID,
                        RangeDay,
                        flag}, this.GetReportFormPDFByReportFormIDOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByReportFormIDOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByReportFormIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByReportFormIDCompleted(this, new GetReportFormPDFByReportFormIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByFormNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByFormNo(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByFormNo", new object[] {
                        FormNo,
                        FormNoFormat,
                        SplitChar,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFormNoAsync(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag) {
            this.GetReportFormPDFByFormNoAsync(FormNo, FormNoFormat, SplitChar, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFormNoAsync(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByFormNoOperationCompleted == null)) {
                this.GetReportFormPDFByFormNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByFormNoOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByFormNo", new object[] {
                        FormNo,
                        FormNoFormat,
                        SplitChar,
                        RangeDay,
                        flag}, this.GetReportFormPDFByFormNoOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByFormNoOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByFormNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByFormNoCompleted(this, new GetReportFormPDFByFormNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByBarCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByBarCode(string BarCode, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByBarCode", new object[] {
                        BarCode,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByBarCodeAsync(string BarCode, int RangeDay, int flag) {
            this.GetReportFormPDFByBarCodeAsync(BarCode, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByBarCodeAsync(string BarCode, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByBarCodeOperationCompleted == null)) {
                this.GetReportFormPDFByBarCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByBarCodeOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByBarCode", new object[] {
                        BarCode,
                        RangeDay,
                        flag}, this.GetReportFormPDFByBarCodeOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByBarCodeOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByBarCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByBarCodeCompleted(this, new GetReportFormPDFByBarCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByPatNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByPatNo(string PatNo, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByPatNo", new object[] {
                        PatNo,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByPatNoAsync(string PatNo, int RangeDay, int flag) {
            this.GetReportFormPDFByPatNoAsync(PatNo, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByPatNoAsync(string PatNo, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByPatNoOperationCompleted == null)) {
                this.GetReportFormPDFByPatNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByPatNoOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByPatNo", new object[] {
                        PatNo,
                        RangeDay,
                        flag}, this.GetReportFormPDFByPatNoOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByPatNoOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByPatNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByPatNoCompleted(this, new GetReportFormPDFByPatNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByZDY17", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByZDY17(string ZDY17, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByZDY17", new object[] {
                        ZDY17,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByZDY17Async(string ZDY17, int RangeDay, int flag) {
            this.GetReportFormPDFByZDY17Async(ZDY17, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByZDY17Async(string ZDY17, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByZDY17OperationCompleted == null)) {
                this.GetReportFormPDFByZDY17OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByZDY17OperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByZDY17", new object[] {
                        ZDY17,
                        RangeDay,
                        flag}, this.GetReportFormPDFByZDY17OperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByZDY17OperationCompleted(object arg) {
            if ((this.GetReportFormPDFByZDY17Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByZDY17Completed(this, new GetReportFormPDFByZDY17CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByFields", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByFields(string[] fields, string[] values, string[] order, int RangeDay, int IsPrintTimes, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByFields", new object[] {
                        fields,
                        values,
                        order,
                        RangeDay,
                        IsPrintTimes,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFieldsAsync(string[] fields, string[] values, string[] order, int RangeDay, int IsPrintTimes, int flag) {
            this.GetReportFormPDFByFieldsAsync(fields, values, order, RangeDay, IsPrintTimes, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFieldsAsync(string[] fields, string[] values, string[] order, int RangeDay, int IsPrintTimes, int flag, object userState) {
            if ((this.GetReportFormPDFByFieldsOperationCompleted == null)) {
                this.GetReportFormPDFByFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByFieldsOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByFields", new object[] {
                        fields,
                        values,
                        order,
                        RangeDay,
                        IsPrintTimes,
                        flag}, this.GetReportFormPDFByFieldsOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByFieldsOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByFieldsCompleted(this, new GetReportFormPDFByFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateReportPrintTimes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateReportPrintTimes(string reportformidstr, out string ErrorInfo) {
            object[] results = this.Invoke("UpdateReportPrintTimes", new object[] {
                        reportformidstr});
            ErrorInfo = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateReportPrintTimesAsync(string reportformidstr) {
            this.UpdateReportPrintTimesAsync(reportformidstr, null);
        }
        
        /// <remarks/>
        public void UpdateReportPrintTimesAsync(string reportformidstr, object userState) {
            if ((this.UpdateReportPrintTimesOperationCompleted == null)) {
                this.UpdateReportPrintTimesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateReportPrintTimesOperationCompleted);
            }
            this.InvokeAsync("UpdateReportPrintTimes", new object[] {
                        reportformidstr}, this.UpdateReportPrintTimesOperationCompleted, userState);
        }
        
        private void OnUpdateReportPrintTimesOperationCompleted(object arg) {
            if ((this.UpdateReportPrintTimesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateReportPrintTimesCompleted(this, new UpdateReportPrintTimesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByReportFormID_FTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByReportFormID_FTP(string ReportFormID, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByReportFormID_FTP", new object[] {
                        ReportFormID,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByReportFormID_FTPAsync(string ReportFormID, int RangeDay, int flag) {
            this.GetReportFormPDFByReportFormID_FTPAsync(ReportFormID, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByReportFormID_FTPAsync(string ReportFormID, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByReportFormID_FTPOperationCompleted == null)) {
                this.GetReportFormPDFByReportFormID_FTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByReportFormID_FTPOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByReportFormID_FTP", new object[] {
                        ReportFormID,
                        RangeDay,
                        flag}, this.GetReportFormPDFByReportFormID_FTPOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByReportFormID_FTPOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByReportFormID_FTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByReportFormID_FTPCompleted(this, new GetReportFormPDFByReportFormID_FTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByFormNo_FTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByFormNo_FTP(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag, out string[] ReportFormPdfPath, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByFormNo_FTP", new object[] {
                        FormNo,
                        FormNoFormat,
                        SplitChar,
                        RangeDay,
                        flag});
            ReportFormPdfPath = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFormNo_FTPAsync(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag) {
            this.GetReportFormPDFByFormNo_FTPAsync(FormNo, FormNoFormat, SplitChar, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFormNo_FTPAsync(string FormNo, string FormNoFormat, string SplitChar, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormPDFByFormNo_FTPOperationCompleted == null)) {
                this.GetReportFormPDFByFormNo_FTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByFormNo_FTPOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByFormNo_FTP", new object[] {
                        FormNo,
                        FormNoFormat,
                        SplitChar,
                        RangeDay,
                        flag}, this.GetReportFormPDFByFormNo_FTPOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByFormNo_FTPOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByFormNo_FTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByFormNo_FTPCompleted(this, new GetReportFormPDFByFormNo_FTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateReportPrintTimesByFormId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateReportPrintTimesByFormId(string reportformidstr, out string ErrorInfo) {
            object[] results = this.Invoke("UpdateReportPrintTimesByFormId", new object[] {
                        reportformidstr});
            ErrorInfo = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateReportPrintTimesByFormIdAsync(string reportformidstr) {
            this.UpdateReportPrintTimesByFormIdAsync(reportformidstr, null);
        }
        
        /// <remarks/>
        public void UpdateReportPrintTimesByFormIdAsync(string reportformidstr, object userState) {
            if ((this.UpdateReportPrintTimesByFormIdOperationCompleted == null)) {
                this.UpdateReportPrintTimesByFormIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateReportPrintTimesByFormIdOperationCompleted);
            }
            this.InvokeAsync("UpdateReportPrintTimesByFormId", new object[] {
                        reportformidstr}, this.UpdateReportPrintTimesByFormIdOperationCompleted, userState);
        }
        
        private void OnUpdateReportPrintTimesByFormIdOperationCompleted(object arg) {
            if ((this.UpdateReportPrintTimesByFormIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateReportPrintTimesByFormIdCompleted(this, new UpdateReportPrintTimesByFormIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormBitsPDFByPatNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormBitsPDFByPatNo(string PatNo, int RangeDay, int flag, out string[] ReportFormPdfBits, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormBitsPDFByPatNo", new object[] {
                        PatNo,
                        RangeDay,
                        flag});
            ReportFormPdfBits = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormBitsPDFByPatNoAsync(string PatNo, int RangeDay, int flag) {
            this.GetReportFormBitsPDFByPatNoAsync(PatNo, RangeDay, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormBitsPDFByPatNoAsync(string PatNo, int RangeDay, int flag, object userState) {
            if ((this.GetReportFormBitsPDFByPatNoOperationCompleted == null)) {
                this.GetReportFormBitsPDFByPatNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormBitsPDFByPatNoOperationCompleted);
            }
            this.InvokeAsync("GetReportFormBitsPDFByPatNo", new object[] {
                        PatNo,
                        RangeDay,
                        flag}, this.GetReportFormBitsPDFByPatNoOperationCompleted, userState);
        }
        
        private void OnGetReportFormBitsPDFByPatNoOperationCompleted(object arg) {
            if ((this.GetReportFormBitsPDFByPatNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormBitsPDFByPatNoCompleted(this, new GetReportFormBitsPDFByPatNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportFormPDFByFields_Base64String", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetReportFormPDFByFields_Base64String(string[] fields, string[] values, string[] order, int RangeDay, int IsPrintTimes, int flag, out string[] ReportFormPdfPathBtis, out string ErrorInfo) {
            object[] results = this.Invoke("GetReportFormPDFByFields_Base64String", new object[] {
                        fields,
                        values,
                        order,
                        RangeDay,
                        IsPrintTimes,
                        flag});
            ReportFormPdfPathBtis = ((string[])(results[1]));
            ErrorInfo = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFields_Base64StringAsync(string[] fields, string[] values, string[] order, int RangeDay, int IsPrintTimes, int flag) {
            this.GetReportFormPDFByFields_Base64StringAsync(fields, values, order, RangeDay, IsPrintTimes, flag, null);
        }
        
        /// <remarks/>
        public void GetReportFormPDFByFields_Base64StringAsync(string[] fields, string[] values, string[] order, int RangeDay, int IsPrintTimes, int flag, object userState) {
            if ((this.GetReportFormPDFByFields_Base64StringOperationCompleted == null)) {
                this.GetReportFormPDFByFields_Base64StringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportFormPDFByFields_Base64StringOperationCompleted);
            }
            this.InvokeAsync("GetReportFormPDFByFields_Base64String", new object[] {
                        fields,
                        values,
                        order,
                        RangeDay,
                        IsPrintTimes,
                        flag}, this.GetReportFormPDFByFields_Base64StringOperationCompleted, userState);
        }
        
        private void OnGetReportFormPDFByFields_Base64StringOperationCompleted(object arg) {
            if ((this.GetReportFormPDFByFields_Base64StringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportFormPDFByFields_Base64StringCompleted(this, new GetReportFormPDFByFields_Base64StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByReportFormIDCompletedEventHandler(object sender, GetReportFormPDFByReportFormIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByReportFormIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByReportFormIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByFormNoCompletedEventHandler(object sender, GetReportFormPDFByFormNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByFormNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByFormNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByBarCodeCompletedEventHandler(object sender, GetReportFormPDFByBarCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByBarCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByBarCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByPatNoCompletedEventHandler(object sender, GetReportFormPDFByPatNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByPatNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByPatNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByZDY17CompletedEventHandler(object sender, GetReportFormPDFByZDY17CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByZDY17CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByZDY17CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByFieldsCompletedEventHandler(object sender, GetReportFormPDFByFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateReportPrintTimesCompletedEventHandler(object sender, UpdateReportPrintTimesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateReportPrintTimesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateReportPrintTimesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByReportFormID_FTPCompletedEventHandler(object sender, GetReportFormPDFByReportFormID_FTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByReportFormID_FTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByReportFormID_FTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByFormNo_FTPCompletedEventHandler(object sender, GetReportFormPDFByFormNo_FTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByFormNo_FTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByFormNo_FTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPath {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateReportPrintTimesByFormIdCompletedEventHandler(object sender, UpdateReportPrintTimesByFormIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateReportPrintTimesByFormIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateReportPrintTimesByFormIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormBitsPDFByPatNoCompletedEventHandler(object sender, GetReportFormBitsPDFByPatNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormBitsPDFByPatNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormBitsPDFByPatNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfBits {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportFormPDFByFields_Base64StringCompletedEventHandler(object sender, GetReportFormPDFByFields_Base64StringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportFormPDFByFields_Base64StringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportFormPDFByFields_Base64StringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string[] ReportFormPdfPathBtis {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591