{
	success:true,
	ResultDataValue:{
		count:10,
		list:[{
			TestEquipItemGoods_TestEquipItem_TestEquip_CName:'测试仪器1',
			TestEquipItemGoods_TestEquipItem_Item_CName:'测试项目1',
			TestEquipItemGoods_Goods_CName:'测试试剂1',
			TestEquipItemGoods_StartDate:'2016-01-01',
			TestEquipItemGoods_EndDate:'',
			TestEquipItemGoods_Visible:'1',
			TestEquipItemGoods:'1'
		},{
			TestEquipItemGoods_TestEquipItem_TestEquip_CName:'测试仪器1',
			TestEquipItemGoods_TestEquipItem_Item_CName:'测试项目1',
			TestEquipItemGoods_Goods_CName:'测试试剂2',
			TestEquipItemGoods_StartDate:'2016-01-01',
			TestEquipItemGoods_EndDate:'',
			TestEquipItemGoods_Visible:'1',
			TestEquipItemGoods:'2'
		}]
	}
}
