//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiFang.BLL.OA.OALSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OALSR.IOAL")]
    public interface IOAL {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAL/GetCharLicenceByMAC", ReplyAction="http://tempuri.org/IOAL/GetCharLicenceByMACResponse")]
        string GetCharLicenceByMAC(string pLicenceType, string pMAC, string pSQH, string pBeginDate, string pENDDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAL/GetNumLicence", ReplyAction="http://tempuri.org/IOAL/GetNumLicenceResponse")]
        string GetNumLicence(string pLicenceType, string serverNo, string Mac, string clientName, string pSQH, string pSNo, string pENDDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOAL/GetNumLicenceByMAC", ReplyAction="http://tempuri.org/IOAL/GetNumLicenceByMACResponse")]
        string GetNumLicenceByMAC(string pLicenceType, string pMAC, string pSQH, string pBeginDate, string pENDDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOALChannel : ZhiFang.BLL.OA.OALSR.IOAL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OALClient : System.ServiceModel.ClientBase<ZhiFang.BLL.OA.OALSR.IOAL>, ZhiFang.BLL.OA.OALSR.IOAL {
        
        public OALClient() {
        }
        
        public OALClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OALClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OALClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OALClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCharLicenceByMAC(string pLicenceType, string pMAC, string pSQH, string pBeginDate, string pENDDate) {
            return base.Channel.GetCharLicenceByMAC(pLicenceType, pMAC, pSQH, pBeginDate, pENDDate);
        }
        
        public string GetNumLicence(string pLicenceType, string serverNo, string Mac, string clientName, string pSQH, string pSNo, string pENDDate) {
            return base.Channel.GetNumLicence(pLicenceType, serverNo, Mac, clientName, pSQH, pSNo, pENDDate);
        }
        
        public string GetNumLicenceByMAC(string pLicenceType, string pMAC, string pSQH, string pBeginDate, string pENDDate) {
            return base.Channel.GetNumLicenceByMAC(pLicenceType, pMAC, pSQH, pBeginDate, pENDDate);
        }
    }
}
