//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.BaseResultDataValue))]
    public partial class BaseResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorInfo {
            get {
                return this.ErrorInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorInfoField, value) != true)) {
                    this.ErrorInfoField = value;
                    this.RaisePropertyChanged("ErrorInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResultDataValue", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BaseResultDataValue : ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.BaseResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDataFormatTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDataValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultDataFormatType {
            get {
                return this.ResultDataFormatTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDataFormatTypeField, value) != true)) {
                    this.ResultDataFormatTypeField = value;
                    this.RaisePropertyChanged("ResultDataFormatType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultDataValue {
            get {
                return this.ResultDataValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDataValueField, value) != true)) {
                    this.ResultDataValueField = value;
                    this.RaisePropertyChanged("ResultDataValue");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_ZFClient.ZFClientServiceSoap")]
    public interface ZFClientServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 RS_UDTO_AutoCheckOrderDocResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RS_UDTO_AutoCheckOrderDoc", ReplyAction="*")]
        ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocResponse RS_UDTO_AutoCheckOrderDoc(ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RS_UDTO_AutoCheckOrderDocPush", ReplyAction="*")]
        void RS_UDTO_AutoCheckOrderDocPush(long orderDocId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RS_UDTO_AutoCheckOrderDocRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RS_UDTO_AutoCheckOrderDoc", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocRequestBody Body;
        
        public RS_UDTO_AutoCheckOrderDocRequest() {
        }
        
        public RS_UDTO_AutoCheckOrderDocRequest(ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RS_UDTO_AutoCheckOrderDocRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long orderDocId;
        
        public RS_UDTO_AutoCheckOrderDocRequestBody() {
        }
        
        public RS_UDTO_AutoCheckOrderDocRequestBody(long orderDocId) {
            this.orderDocId = orderDocId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RS_UDTO_AutoCheckOrderDocResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RS_UDTO_AutoCheckOrderDocResponse", Namespace="http://tempuri.org/", Order=0)]
        public ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocResponseBody Body;
        
        public RS_UDTO_AutoCheckOrderDocResponse() {
        }
        
        public RS_UDTO_AutoCheckOrderDocResponse(ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RS_UDTO_AutoCheckOrderDocResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.BaseResultDataValue RS_UDTO_AutoCheckOrderDocResult;
        
        public RS_UDTO_AutoCheckOrderDocResponseBody() {
        }
        
        public RS_UDTO_AutoCheckOrderDocResponseBody(ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.BaseResultDataValue RS_UDTO_AutoCheckOrderDocResult) {
            this.RS_UDTO_AutoCheckOrderDocResult = RS_UDTO_AutoCheckOrderDocResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZFClientServiceSoapChannel : ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.ZFClientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZFClientServiceSoapClient : System.ServiceModel.ClientBase<ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.ZFClientServiceSoap>, ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.ZFClientServiceSoap {
        
        public ZFClientServiceSoapClient() {
        }
        
        public ZFClientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZFClientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZFClientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZFClientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocResponse ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.ZFClientServiceSoap.RS_UDTO_AutoCheckOrderDoc(ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocRequest request) {
            return base.Channel.RS_UDTO_AutoCheckOrderDoc(request);
        }
        
        public ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.BaseResultDataValue RS_UDTO_AutoCheckOrderDoc(long orderDocId) {
            ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocRequest inValue = new ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocRequest();
            inValue.Body = new ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocRequestBody();
            inValue.Body.orderDocId = orderDocId;
            ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.RS_UDTO_AutoCheckOrderDocResponse retVal = ((ZhiFang.Digitlab.ReagentSys.ServiceReference_ZFClient.ZFClientServiceSoap)(this)).RS_UDTO_AutoCheckOrderDoc(inValue);
            return retVal.Body.RS_UDTO_AutoCheckOrderDocResult;
        }
        
        public void RS_UDTO_AutoCheckOrderDocPush(long orderDocId) {
            base.Channel.RS_UDTO_AutoCheckOrderDocPush(orderDocId);
        }
    }
}
